# Project3: Twitter Sentiment Analysis

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
#necessary common imports:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [3]:
# For text preprocessing:
import re #regex module
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
import string

# Required downloadable packages:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\johnd\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\johnd\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\johnd\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

## Reading the Data from the Given excel file:

In [4]:
# Loading the data:
data = pd.read_csv('Twitter_Data.csv')
data.head()

clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162980 entries, 0 to 162979
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   clean_text  162976 non-null  object 
 1   category    162973 non-null  float64
dtypes: float64(1), object(1)
memory usage: 2.5+ MB


In [6]:
data.shape

(162980, 2)

## Changing our dependent variable into categorical. (0 to “Neutral,”-1 to “Negative”, 1 to “Positive”):

In [7]:
data.category.value_counts()

 1.0    72250
 0.0    55213
-1.0    35510
Name: category, dtype: int64

In [8]:
mapping = {0:"Neutral", 1:"Positive",-1:"Negative"}

In [9]:
data['category'] = data['category'].replace(mapping)

In [10]:
data.category.value_counts()

Positive    72250
Neutral     55213
Negative    35510
Name: category, dtype: int64

## Performing missing value analysis and dropping all null/missing values:

In [11]:
data.isna().sum() #reviewing null values

clean_text    4
category      7
dtype: int64

In [12]:
data.dropna(inplace=True)

In [13]:
data.isna().sum() #again reviewing, no null values present.

clean_text    0
category      0
dtype: int64

In [14]:
data.shape

(162969, 2)

In [15]:
#renaming the column name to 'Tweets'
data = data.rename(columns={'clean_text': 'Tweets'})

## Performing text cleaning. (removing every symbol except alphanumeric, transforming all words to lower case, and removing punctuation and stopwords ):

In [16]:
# For text-preprocessing:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
import string

# For model building:
from keras.models import Sequential
from keras.layers import Input, Dense, Embedding, LSTM, Dropout

punct = string.punctuation #storing all punctuations
punct

In [17]:
# Stopwords list:
stopWords = stopwords.words('english')
print(stopWords)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [18]:
## Reviewing the first record:
#data['clean_text'][0]
data['Tweets'][0]

'when modi promised “minimum government maximum governance” expected him begin the difficult job reforming the state why does take years get justice state should and not business and should exit psus and temples'

#### Text-preprocessing steps:

In [19]:
def cleaning(text):
    # Removes all non-alphabetic characters
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Convert to lowercase
    text = text.lower()
    # Remove extra whitespaces
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [20]:
#data['clean_text'] = data['clean_text'].apply(cleaning)
data['Tweets'] = data['Tweets'].apply(cleaning)

In [21]:
#data['clean_text'][0]
data['Tweets'][0]

'when modi promised minimum government maximum governance expected him begin the difficult job reforming the state why does take years get justice state should and not business and should exit psus and temples'

In [22]:
def processing_text(text):
    # Tokenize the text
    tokens = word_tokenize(text)
    
    # Remove stopwords
    stop_words = set(stopWords)
    filtered_tokens = [token for token in tokens if token not in stop_words]
    
    # Apply stemming
    stemmer = PorterStemmer()
    stemmed_tokens = [stemmer.stem(token) for token in filtered_tokens]
    
    # Apply lemmatization
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in stemmed_tokens]
    
    # Join the tokens back into a string and return it
    return ' '.join(lemmatized_tokens)

In [23]:
#data['clean_text'] = data['clean_text'].apply(processing_text)
data['Tweets'] = data['Tweets'].apply(processing_text)

In [24]:
# data['clean_text'][0]
data['Tweets'][0]

'modi promis minimum govern maximum govern expect begin difficult job reform state take year get justic state busi exit psu templ'

## Splitting data into dependent(Y) and independent(X) sets:

In [25]:
X = data.Tweets
Y = data.category

In [26]:
sequences = X.copy()

## Performing operations on text data:

### * Performing one-hot encoding for each sentence(using TensorFlow):

In [27]:
from keras.preprocessing.text import one_hot
one_hot_encoded = []

for word in sequences:
    vocab_size = 2000
    encoded_words = one_hot(word, vocab_size)
    one_hot_encoded.append(encoded_words)

In [28]:
print(one_hot_encoded[0])

[1001, 1495, 1197, 296, 1257, 296, 738, 431, 142, 1778, 1930, 1429, 1718, 851, 342, 1950, 1429, 424, 377, 558, 1849]


### * Adding padding from the front side (using Tensorflow):

In [29]:
from keras.preprocessing.sequence import pad_sequences
max_length =  30
seq_mat = pad_sequences(one_hot_encoded, maxlen=max_length)
#seq_mat

In [30]:
seq_mat[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0, 1001, 1495,
       1197,  296, 1257,  296,  738,  431,  142, 1778, 1930, 1429, 1718,
        851,  342, 1950, 1429,  424,  377,  558, 1849])

### * Building an LSTM model and compiling it(describing features, input length,vocabulary size, information drop-out layer, activation function for output)

In [31]:
## This is the finalized model I'm gonna use for the project......
from keras.layers import Input, Dense, Embedding, LSTM, Dropout
from keras.models import Sequential, Model

model = Sequential() #step1: instantiating the model function
model.add(Input(30,)) # step2: adding input layer of 30 input size
model.add(Embedding(input_dim=vocab_size, output_dim=32)) # step3: adding embedding layer, giving input dim, output dim
model.add(LSTM(units=64)) #step4: adding LSTM layer with 64 neurons
model.add(Dropout(rate=0.5)) #step5: dropping some neurons
model.add(Dense(units=3, activation='sigmoid')) #step6: output layer, giving out three classification output

In [32]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 30, 32)            64000     
                                                                 
 lstm (LSTM)                 (None, 64)                24832     
                                                                 
 dropout (Dropout)           (None, 64)                0         
                                                                 
 dense (Dense)               (None, 3)                 195       
                                                                 
Total params: 89027 (347.76 KB)
Trainable params: 89027 (347.76 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


vocab_size * output_dim + (4 * 64 * (64 + 30 + 1)) + (64 * 30) + 64 + (3 * 64) + 3

In [33]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [34]:
X_final = seq_mat #creating Final independent variable
#Y = data.category

### * Performing dummy variable creation for the dependent variable:

In [35]:
Y_final = pd.get_dummies(Y) #creating dummy variables/columns from Y
Y_final

Negative  Neutral  Positive
0              1        0         0
1              0        1         0
2              0        0         1
3              0        0         1
4              0        0         1
...          ...      ...       ...
162975         1        0         0
162976         1        0         0
162977         0        1         0
162978         0        1         0
162979         0        0         1

[162969 rows x 3 columns]

### * Splitting the data into tests and train:

In [36]:
#splitting into 70%-30% ratio
X_train, X_test, Y_train, Y_test = train_test_split(X_final, Y_final, test_size=0.3) 

## Training new model:

    model.fit(X_train, Y_train)
    3565/3565 [==============================] - 160s 43ms/step - loss: 0.4360 - accuracy: 0.6980
    <keras.src.callbacks.History at 0x177325866e0>

In [37]:
# Fitting training set and giving validation_split of 10%:
model.fit(X_train, Y_train, batch_size=80, epochs=10,  validation_split=0.1)

Epoch 1/10
1284/1284 [==============================] - 88s 64ms/step - loss: 0.4514 - accuracy: 0.6808 - val_loss: 0.4058 - val_accuracy: 0.7227
Epoch 2/10
1284/1284 [==============================] - 81s 63ms/step - loss: 0.3963 - accuracy: 0.7346 - val_loss: 0.3960 - val_accuracy: 0.7266
Epoch 3/10
1284/1284 [==============================] - 89s 70ms/step - loss: 0.3872 - accuracy: 0.7397 - val_loss: 0.3941 - val_accuracy: 0.7273
Epoch 4/10
1284/1284 [==============================] - 84s 65ms/step - loss: 0.3787 - accuracy: 0.7444 - val_loss: 0.3923 - val_accuracy: 0.7282
Epoch 5/10
1284/1284 [==============================] - 86s 67ms/step - loss: 0.3703 - accuracy: 0.7498 - val_loss: 0.3932 - val_accuracy: 0.7261
Epoch 6/10
1284/1284 [==============================] - 105s 82ms/step - loss: 0.3634 - accuracy: 0.7562 - val_loss: 0.3949 - val_accuracy: 0.7347
Epoch 7/10
1284/1284 [==============================] - 97s 75ms/step - loss: 0.3566 - accuracy: 0.7617 - val_loss: 0.3956 

In [38]:
#Evaluating our model by providing test data:
model.evaluate(X_test, Y_test)

1528/1528 [==============================] - 23s 15ms/step - loss: 0.4028 - accuracy: 0.7354


[0.40280699729919434, 0.7353705167770386]

In [39]:
# Generating predictions:
acc = model.predict(X_test)

1528/1528 [==============================] - 24s 15ms/step


In [40]:
#Checking its type:
type(acc)

numpy.ndarray

In [41]:
# Reviewing first 10 records:
acc[:10]

array([[0.00459016, 0.00321639, 0.99394584],
       [0.1358922 , 0.07370602, 0.76688546],
       [0.00224614, 0.98353314, 0.0236471 ],
       [0.2235105 , 0.04992226, 0.7181809 ],
       [0.9159823 , 0.10393535, 0.01837717],
       [0.43619904, 0.3805365 , 0.20339786],
       [0.21304017, 0.42884645, 0.21677402],
       [0.09843527, 0.20717186, 0.6802411 ],
       [0.74473965, 0.14254755, 0.07890027],
       [0.22839625, 0.09501585, 0.6831377 ]], dtype=float32)

In [42]:
pred = acc.copy() #copying
pred[0] #first record

array([0.00459016, 0.00321639, 0.99394584], dtype=float32)

## Normalizing the predictions as same as the original data (predictions might be in decimal, so whatsoever is nearest to 1 is predicted as yes and set other as 0):

In [43]:
count = 0
for i in range(len(pred)):
    if (pred[i][0] > pred[i][1] and pred[i][0] > pred[i][2]):
        count = 0
    elif (pred[i][1] > pred[i][0] and pred[i][1] > pred[i][2]):
        count = 1
    elif (pred[i][2] > pred[i][0] and pred[i][2] > pred[i][1]):
        count = 2
    print(i,"for count is",count)   
    for j in range(3):
        pred[i][j] = 0   
        pred[i][count] = 1
    print(pred[i])
    count = 0

0 for count is 2
[0. 0. 1.]
1 for count is 2
[0. 0. 1.]
2 for count is 1
[0. 1. 0.]
3 for count is 2
[0. 0. 1.]
4 for count is 0
[1. 0. 0.]
5 for count is 0
[1. 0. 0.]
6 for count is 1
[0. 1. 0.]
7 for count is 2
[0. 0. 1.]
8 for count is 0
[1. 0. 0.]
9 for count is 2
[0. 0. 1.]
10 for count is 1
[0. 1. 0.]
11 for count is 0
[1. 0. 0.]
12 for count is 2
[0. 0. 1.]
13 for count is 2
[0. 0. 1.]
14 for count is 1
[0. 1. 0.]
15 for count is 2
[0. 0. 1.]
16 for count is 1
[0. 1. 0.]
17 for count is 0
[1. 0. 0.]
18 for count is 2
[0. 0. 1.]
19 for count is 2
[0. 0. 1.]
20 for count is 2
[0. 0. 1.]
21 for count is 1
[0. 1. 0.]
22 for count is 1
[0. 1. 0.]
23 for count is 0
[1. 0. 0.]
24 for count is 2
[0. 0. 1.]
25 for count is 1
[0. 1. 0.]
26 for count is 2
[0. 0. 1.]
27 for count is 2
[0. 0. 1.]
28 for count is 0
[1. 0. 0.]
29 for count is 2
[0. 0. 1.]
30 for count is 2
[0. 0. 1.]
31 for count is 2
[0. 0. 1.]
32 for count is 0
[1. 0. 0.]
33 for count is 2
[0. 0. 1.]
34 for count is 1
[0. 1.

[0. 1. 0.]
673 for count is 2
[0. 0. 1.]
674 for count is 1
[0. 1. 0.]
675 for count is 2
[0. 0. 1.]
676 for count is 2
[0. 0. 1.]
677 for count is 2
[0. 0. 1.]
678 for count is 2
[0. 0. 1.]
679 for count is 2
[0. 0. 1.]
680 for count is 0
[1. 0. 0.]
681 for count is 1
[0. 1. 0.]
682 for count is 2
[0. 0. 1.]
683 for count is 0
[1. 0. 0.]
684 for count is 2
[0. 0. 1.]
685 for count is 2
[0. 0. 1.]
686 for count is 1
[0. 1. 0.]
687 for count is 1
[0. 1. 0.]
688 for count is 0
[1. 0. 0.]
689 for count is 2
[0. 0. 1.]
690 for count is 2
[0. 0. 1.]
691 for count is 2
[0. 0. 1.]
692 for count is 1
[0. 1. 0.]
693 for count is 1
[0. 1. 0.]
694 for count is 2
[0. 0. 1.]
695 for count is 0
[1. 0. 0.]
696 for count is 2
[0. 0. 1.]
697 for count is 2
[0. 0. 1.]
698 for count is 0
[1. 0. 0.]
699 for count is 0
[1. 0. 0.]
700 for count is 1
[0. 1. 0.]
701 for count is 0
[1. 0. 0.]
702 for count is 1
[0. 1. 0.]
703 for count is 0
[1. 0. 0.]
704 for count is 2
[0. 0. 1.]
705 for count is 2
[0. 0. 1.]

[0. 0. 1.]
1438 for count is 0
[1. 0. 0.]
1439 for count is 2
[0. 0. 1.]
1440 for count is 2
[0. 0. 1.]
1441 for count is 1
[0. 1. 0.]
1442 for count is 1
[0. 1. 0.]
1443 for count is 1
[0. 1. 0.]
1444 for count is 2
[0. 0. 1.]
1445 for count is 1
[0. 1. 0.]
1446 for count is 2
[0. 0. 1.]
1447 for count is 2
[0. 0. 1.]
1448 for count is 2
[0. 0. 1.]
1449 for count is 0
[1. 0. 0.]
1450 for count is 0
[1. 0. 0.]
1451 for count is 2
[0. 0. 1.]
1452 for count is 0
[1. 0. 0.]
1453 for count is 1
[0. 1. 0.]
1454 for count is 1
[0. 1. 0.]
1455 for count is 1
[0. 1. 0.]
1456 for count is 0
[1. 0. 0.]
1457 for count is 2
[0. 0. 1.]
1458 for count is 1
[0. 1. 0.]
1459 for count is 0
[1. 0. 0.]
1460 for count is 1
[0. 1. 0.]
1461 for count is 2
[0. 0. 1.]
1462 for count is 2
[0. 0. 1.]
1463 for count is 2
[0. 0. 1.]
1464 for count is 2
[0. 0. 1.]
1465 for count is 2
[0. 0. 1.]
1466 for count is 1
[0. 1. 0.]
1467 for count is 1
[0. 1. 0.]
1468 for count is 1
[0. 1. 0.]
1469 for count is 2
[0. 0. 1

[0. 1. 0.]
2258 for count is 2
[0. 0. 1.]
2259 for count is 1
[0. 1. 0.]
2260 for count is 2
[0. 0. 1.]
2261 for count is 1
[0. 1. 0.]
2262 for count is 2
[0. 0. 1.]
2263 for count is 0
[1. 0. 0.]
2264 for count is 2
[0. 0. 1.]
2265 for count is 1
[0. 1. 0.]
2266 for count is 0
[1. 0. 0.]
2267 for count is 2
[0. 0. 1.]
2268 for count is 1
[0. 1. 0.]
2269 for count is 1
[0. 1. 0.]
2270 for count is 2
[0. 0. 1.]
2271 for count is 1
[0. 1. 0.]
2272 for count is 2
[0. 0. 1.]
2273 for count is 2
[0. 0. 1.]
2274 for count is 1
[0. 1. 0.]
2275 for count is 1
[0. 1. 0.]
2276 for count is 1
[0. 1. 0.]
2277 for count is 0
[1. 0. 0.]
2278 for count is 1
[0. 1. 0.]
2279 for count is 1
[0. 1. 0.]
2280 for count is 2
[0. 0. 1.]
2281 for count is 0
[1. 0. 0.]
2282 for count is 2
[0. 0. 1.]
2283 for count is 2
[0. 0. 1.]
2284 for count is 0
[1. 0. 0.]
2285 for count is 2
[0. 0. 1.]
2286 for count is 2
[0. 0. 1.]
2287 for count is 0
[1. 0. 0.]
2288 for count is 0
[1. 0. 0.]
2289 for count is 0
[1. 0. 0

[0. 0. 1.]
3099 for count is 1
[0. 1. 0.]
3100 for count is 2
[0. 0. 1.]
3101 for count is 2
[0. 0. 1.]
3102 for count is 1
[0. 1. 0.]
3103 for count is 0
[1. 0. 0.]
3104 for count is 1
[0. 1. 0.]
3105 for count is 2
[0. 0. 1.]
3106 for count is 1
[0. 1. 0.]
3107 for count is 1
[0. 1. 0.]
3108 for count is 1
[0. 1. 0.]
3109 for count is 1
[0. 1. 0.]
3110 for count is 2
[0. 0. 1.]
3111 for count is 2
[0. 0. 1.]
3112 for count is 2
[0. 0. 1.]
3113 for count is 2
[0. 0. 1.]
3114 for count is 1
[0. 1. 0.]
3115 for count is 2
[0. 0. 1.]
3116 for count is 1
[0. 1. 0.]
3117 for count is 1
[0. 1. 0.]
3118 for count is 2
[0. 0. 1.]
3119 for count is 2
[0. 0. 1.]
3120 for count is 2
[0. 0. 1.]
3121 for count is 2
[0. 0. 1.]
3122 for count is 2
[0. 0. 1.]
3123 for count is 1
[0. 1. 0.]
3124 for count is 1
[0. 1. 0.]
3125 for count is 2
[0. 0. 1.]
3126 for count is 1
[0. 1. 0.]
3127 for count is 2
[0. 0. 1.]
3128 for count is 2
[0. 0. 1.]
3129 for count is 1
[0. 1. 0.]
3130 for count is 2
[0. 0. 1

[0. 1. 0.]
3562 for count is 1
[0. 1. 0.]
3563 for count is 2
[0. 0. 1.]
3564 for count is 1
[0. 1. 0.]
3565 for count is 1
[0. 1. 0.]
3566 for count is 1
[0. 1. 0.]
3567 for count is 1
[0. 1. 0.]
3568 for count is 1
[0. 1. 0.]
3569 for count is 1
[0. 1. 0.]
3570 for count is 1
[0. 1. 0.]
3571 for count is 1
[0. 1. 0.]
3572 for count is 0
[1. 0. 0.]
3573 for count is 2
[0. 0. 1.]
3574 for count is 2
[0. 0. 1.]
3575 for count is 0
[1. 0. 0.]
3576 for count is 1
[0. 1. 0.]
3577 for count is 1
[0. 1. 0.]
3578 for count is 0
[1. 0. 0.]
3579 for count is 0
[1. 0. 0.]
3580 for count is 2
[0. 0. 1.]
3581 for count is 0
[1. 0. 0.]
3582 for count is 0
[1. 0. 0.]
3583 for count is 0
[1. 0. 0.]
3584 for count is 2
[0. 0. 1.]
3585 for count is 1
[0. 1. 0.]
3586 for count is 0
[1. 0. 0.]
3587 for count is 2
[0. 0. 1.]
3588 for count is 1
[0. 1. 0.]
3589 for count is 1
[0. 1. 0.]
3590 for count is 0
[1. 0. 0.]
3591 for count is 1
[0. 1. 0.]
3592 for count is 2
[0. 0. 1.]
3593 for count is 2
[0. 0. 1

4348 for count is 1
[0. 1. 0.]
4349 for count is 0
[1. 0. 0.]
4350 for count is 0
[1. 0. 0.]
4351 for count is 1
[0. 1. 0.]
4352 for count is 2
[0. 0. 1.]
4353 for count is 2
[0. 0. 1.]
4354 for count is 2
[0. 0. 1.]
4355 for count is 2
[0. 0. 1.]
4356 for count is 2
[0. 0. 1.]
4357 for count is 2
[0. 0. 1.]
4358 for count is 2
[0. 0. 1.]
4359 for count is 1
[0. 1. 0.]
4360 for count is 2
[0. 0. 1.]
4361 for count is 2
[0. 0. 1.]
4362 for count is 0
[1. 0. 0.]
4363 for count is 1
[0. 1. 0.]
4364 for count is 2
[0. 0. 1.]
4365 for count is 0
[1. 0. 0.]
4366 for count is 1
[0. 1. 0.]
4367 for count is 2
[0. 0. 1.]
4368 for count is 2
[0. 0. 1.]
4369 for count is 2
[0. 0. 1.]
4370 for count is 0
[1. 0. 0.]
4371 for count is 2
[0. 0. 1.]
4372 for count is 2
[0. 0. 1.]
4373 for count is 1
[0. 1. 0.]
4374 for count is 1
[0. 1. 0.]
4375 for count is 0
[1. 0. 0.]
4376 for count is 2
[0. 0. 1.]
4377 for count is 1
[0. 1. 0.]
4378 for count is 2
[0. 0. 1.]
4379 for count is 0
[1. 0. 0.]
4380 for

[1. 0. 0.]
5080 for count is 2
[0. 0. 1.]
5081 for count is 2
[0. 0. 1.]
5082 for count is 0
[1. 0. 0.]
5083 for count is 1
[0. 1. 0.]
5084 for count is 1
[0. 1. 0.]
5085 for count is 1
[0. 1. 0.]
5086 for count is 1
[0. 1. 0.]
5087 for count is 0
[1. 0. 0.]
5088 for count is 1
[0. 1. 0.]
5089 for count is 1
[0. 1. 0.]
5090 for count is 1
[0. 1. 0.]
5091 for count is 0
[1. 0. 0.]
5092 for count is 1
[0. 1. 0.]
5093 for count is 1
[0. 1. 0.]
5094 for count is 1
[0. 1. 0.]
5095 for count is 1
[0. 1. 0.]
5096 for count is 2
[0. 0. 1.]
5097 for count is 0
[1. 0. 0.]
5098 for count is 2
[0. 0. 1.]
5099 for count is 1
[0. 1. 0.]
5100 for count is 0
[1. 0. 0.]
5101 for count is 2
[0. 0. 1.]
5102 for count is 2
[0. 0. 1.]
5103 for count is 1
[0. 1. 0.]
5104 for count is 2
[0. 0. 1.]
5105 for count is 0
[1. 0. 0.]
5106 for count is 0
[1. 0. 0.]
5107 for count is 2
[0. 0. 1.]
5108 for count is 1
[0. 1. 0.]
5109 for count is 2
[0. 0. 1.]
5110 for count is 1
[0. 1. 0.]
5111 for count is 1
[0. 1. 0

[0. 0. 1.]
5782 for count is 0
[1. 0. 0.]
5783 for count is 0
[1. 0. 0.]
5784 for count is 2
[0. 0. 1.]
5785 for count is 0
[1. 0. 0.]
5786 for count is 0
[1. 0. 0.]
5787 for count is 0
[1. 0. 0.]
5788 for count is 2
[0. 0. 1.]
5789 for count is 0
[1. 0. 0.]
5790 for count is 1
[0. 1. 0.]
5791 for count is 2
[0. 0. 1.]
5792 for count is 1
[0. 1. 0.]
5793 for count is 1
[0. 1. 0.]
5794 for count is 1
[0. 1. 0.]
5795 for count is 1
[0. 1. 0.]
5796 for count is 1
[0. 1. 0.]
5797 for count is 0
[1. 0. 0.]
5798 for count is 2
[0. 0. 1.]
5799 for count is 2
[0. 0. 1.]
5800 for count is 0
[1. 0. 0.]
5801 for count is 2
[0. 0. 1.]
5802 for count is 0
[1. 0. 0.]
5803 for count is 2
[0. 0. 1.]
5804 for count is 2
[0. 0. 1.]
5805 for count is 1
[0. 1. 0.]
5806 for count is 1
[0. 1. 0.]
5807 for count is 0
[1. 0. 0.]
5808 for count is 2
[0. 0. 1.]
5809 for count is 2
[0. 0. 1.]
5810 for count is 2
[0. 0. 1.]
5811 for count is 2
[0. 0. 1.]
5812 for count is 0
[1. 0. 0.]
5813 for count is 2
[0. 0. 1

[1. 0. 0.]
6389 for count is 1
[0. 1. 0.]
6390 for count is 2
[0. 0. 1.]
6391 for count is 1
[0. 1. 0.]
6392 for count is 2
[0. 0. 1.]
6393 for count is 1
[0. 1. 0.]
6394 for count is 1
[0. 1. 0.]
6395 for count is 2
[0. 0. 1.]
6396 for count is 1
[0. 1. 0.]
6397 for count is 1
[0. 1. 0.]
6398 for count is 1
[0. 1. 0.]
6399 for count is 2
[0. 0. 1.]
6400 for count is 1
[0. 1. 0.]
6401 for count is 2
[0. 0. 1.]
6402 for count is 2
[0. 0. 1.]
6403 for count is 0
[1. 0. 0.]
6404 for count is 2
[0. 0. 1.]
6405 for count is 1
[0. 1. 0.]
6406 for count is 2
[0. 0. 1.]
6407 for count is 1
[0. 1. 0.]
6408 for count is 1
[0. 1. 0.]
6409 for count is 2
[0. 0. 1.]
6410 for count is 2
[0. 0. 1.]
6411 for count is 2
[0. 0. 1.]
6412 for count is 2
[0. 0. 1.]
6413 for count is 2
[0. 0. 1.]
6414 for count is 0
[1. 0. 0.]
6415 for count is 1
[0. 1. 0.]
6416 for count is 2
[0. 0. 1.]
6417 for count is 1
[0. 1. 0.]
6418 for count is 2
[0. 0. 1.]
6419 for count is 0
[1. 0. 0.]
6420 for count is 2
[0. 0. 1

[0. 1. 0.]
6678 for count is 2
[0. 0. 1.]
6679 for count is 2
[0. 0. 1.]
6680 for count is 0
[1. 0. 0.]
6681 for count is 2
[0. 0. 1.]
6682 for count is 1
[0. 1. 0.]
6683 for count is 1
[0. 1. 0.]
6684 for count is 2
[0. 0. 1.]
6685 for count is 1
[0. 1. 0.]
6686 for count is 0
[1. 0. 0.]
6687 for count is 2
[0. 0. 1.]
6688 for count is 2
[0. 0. 1.]
6689 for count is 2
[0. 0. 1.]
6690 for count is 0
[1. 0. 0.]
6691 for count is 2
[0. 0. 1.]
6692 for count is 1
[0. 1. 0.]
6693 for count is 2
[0. 0. 1.]
6694 for count is 2
[0. 0. 1.]
6695 for count is 2
[0. 0. 1.]
6696 for count is 0
[1. 0. 0.]
6697 for count is 1
[0. 1. 0.]
6698 for count is 0
[1. 0. 0.]
6699 for count is 0
[1. 0. 0.]
6700 for count is 1
[0. 1. 0.]
6701 for count is 1
[0. 1. 0.]
6702 for count is 1
[0. 1. 0.]
6703 for count is 2
[0. 0. 1.]
6704 for count is 2
[0. 0. 1.]
6705 for count is 1
[0. 1. 0.]
6706 for count is 1
[0. 1. 0.]
6707 for count is 2
[0. 0. 1.]
6708 for count is 1
[0. 1. 0.]
6709 for count is 0
[1. 0. 0

[0. 0. 1.]
7315 for count is 2
[0. 0. 1.]
7316 for count is 2
[0. 0. 1.]
7317 for count is 0
[1. 0. 0.]
7318 for count is 0
[1. 0. 0.]
7319 for count is 1
[0. 1. 0.]
7320 for count is 1
[0. 1. 0.]
7321 for count is 0
[1. 0. 0.]
7322 for count is 0
[1. 0. 0.]
7323 for count is 0
[1. 0. 0.]
7324 for count is 1
[0. 1. 0.]
7325 for count is 0
[1. 0. 0.]
7326 for count is 0
[1. 0. 0.]
7327 for count is 2
[0. 0. 1.]
7328 for count is 1
[0. 1. 0.]
7329 for count is 2
[0. 0. 1.]
7330 for count is 0
[1. 0. 0.]
7331 for count is 2
[0. 0. 1.]
7332 for count is 2
[0. 0. 1.]
7333 for count is 1
[0. 1. 0.]
7334 for count is 1
[0. 1. 0.]
7335 for count is 2
[0. 0. 1.]
7336 for count is 0
[1. 0. 0.]
7337 for count is 1
[0. 1. 0.]
7338 for count is 0
[1. 0. 0.]
7339 for count is 1
[0. 1. 0.]
7340 for count is 2
[0. 0. 1.]
7341 for count is 1
[0. 1. 0.]
7342 for count is 2
[0. 0. 1.]
7343 for count is 1
[0. 1. 0.]
7344 for count is 0
[1. 0. 0.]
7345 for count is 2
[0. 0. 1.]
7346 for count is 0
[1. 0. 0

[1. 0. 0.]
8212 for count is 1
[0. 1. 0.]
8213 for count is 0
[1. 0. 0.]
8214 for count is 2
[0. 0. 1.]
8215 for count is 1
[0. 1. 0.]
8216 for count is 1
[0. 1. 0.]
8217 for count is 2
[0. 0. 1.]
8218 for count is 2
[0. 0. 1.]
8219 for count is 0
[1. 0. 0.]
8220 for count is 1
[0. 1. 0.]
8221 for count is 1
[0. 1. 0.]
8222 for count is 2
[0. 0. 1.]
8223 for count is 2
[0. 0. 1.]
8224 for count is 2
[0. 0. 1.]
8225 for count is 0
[1. 0. 0.]
8226 for count is 0
[1. 0. 0.]
8227 for count is 1
[0. 1. 0.]
8228 for count is 2
[0. 0. 1.]
8229 for count is 1
[0. 1. 0.]
8230 for count is 2
[0. 0. 1.]
8231 for count is 1
[0. 1. 0.]
8232 for count is 1
[0. 1. 0.]
8233 for count is 2
[0. 0. 1.]
8234 for count is 2
[0. 0. 1.]
8235 for count is 1
[0. 1. 0.]
8236 for count is 1
[0. 1. 0.]
8237 for count is 1
[0. 1. 0.]
8238 for count is 2
[0. 0. 1.]
8239 for count is 1
[0. 1. 0.]
8240 for count is 2
[0. 0. 1.]
8241 for count is 0
[1. 0. 0.]
8242 for count is 0
[1. 0. 0.]
8243 for count is 2
[0. 0. 1

[0. 1. 0.]
8720 for count is 2
[0. 0. 1.]
8721 for count is 1
[0. 1. 0.]
8722 for count is 2
[0. 0. 1.]
8723 for count is 2
[0. 0. 1.]
8724 for count is 0
[1. 0. 0.]
8725 for count is 2
[0. 0. 1.]
8726 for count is 0
[1. 0. 0.]
8727 for count is 2
[0. 0. 1.]
8728 for count is 2
[0. 0. 1.]
8729 for count is 1
[0. 1. 0.]
8730 for count is 2
[0. 0. 1.]
8731 for count is 2
[0. 0. 1.]
8732 for count is 1
[0. 1. 0.]
8733 for count is 2
[0. 0. 1.]
8734 for count is 0
[1. 0. 0.]
8735 for count is 1
[0. 1. 0.]
8736 for count is 2
[0. 0. 1.]
8737 for count is 0
[1. 0. 0.]
8738 for count is 1
[0. 1. 0.]
8739 for count is 2
[0. 0. 1.]
8740 for count is 2
[0. 0. 1.]
8741 for count is 0
[1. 0. 0.]
8742 for count is 0
[1. 0. 0.]
8743 for count is 1
[0. 1. 0.]
8744 for count is 2
[0. 0. 1.]
8745 for count is 0
[1. 0. 0.]
8746 for count is 1
[0. 1. 0.]
8747 for count is 1
[0. 1. 0.]
8748 for count is 1
[0. 1. 0.]
8749 for count is 0
[1. 0. 0.]
8750 for count is 2
[0. 0. 1.]
8751 for count is 1
[0. 1. 0

[1. 0. 0.]
9238 for count is 2
[0. 0. 1.]
9239 for count is 1
[0. 1. 0.]
9240 for count is 1
[0. 1. 0.]
9241 for count is 2
[0. 0. 1.]
9242 for count is 2
[0. 0. 1.]
9243 for count is 1
[0. 1. 0.]
9244 for count is 1
[0. 1. 0.]
9245 for count is 2
[0. 0. 1.]
9246 for count is 1
[0. 1. 0.]
9247 for count is 2
[0. 0. 1.]
9248 for count is 2
[0. 0. 1.]
9249 for count is 2
[0. 0. 1.]
9250 for count is 1
[0. 1. 0.]
9251 for count is 1
[0. 1. 0.]
9252 for count is 0
[1. 0. 0.]
9253 for count is 1
[0. 1. 0.]
9254 for count is 0
[1. 0. 0.]
9255 for count is 1
[0. 1. 0.]
9256 for count is 1
[0. 1. 0.]
9257 for count is 1
[0. 1. 0.]
9258 for count is 2
[0. 0. 1.]
9259 for count is 1
[0. 1. 0.]
9260 for count is 0
[1. 0. 0.]
9261 for count is 2
[0. 0. 1.]
9262 for count is 2
[0. 0. 1.]
9263 for count is 0
[1. 0. 0.]
9264 for count is 1
[0. 1. 0.]
9265 for count is 2
[0. 0. 1.]
9266 for count is 1
[0. 1. 0.]
9267 for count is 1
[0. 1. 0.]
9268 for count is 0
[1. 0. 0.]
9269 for count is 2
[0. 0. 1

[1. 0. 0.]
9872 for count is 0
[1. 0. 0.]
9873 for count is 0
[1. 0. 0.]
9874 for count is 2
[0. 0. 1.]
9875 for count is 1
[0. 1. 0.]
9876 for count is 2
[0. 0. 1.]
9877 for count is 1
[0. 1. 0.]
9878 for count is 2
[0. 0. 1.]
9879 for count is 2
[0. 0. 1.]
9880 for count is 2
[0. 0. 1.]
9881 for count is 1
[0. 1. 0.]
9882 for count is 2
[0. 0. 1.]
9883 for count is 1
[0. 1. 0.]
9884 for count is 0
[1. 0. 0.]
9885 for count is 2
[0. 0. 1.]
9886 for count is 2
[0. 0. 1.]
9887 for count is 2
[0. 0. 1.]
9888 for count is 1
[0. 1. 0.]
9889 for count is 1
[0. 1. 0.]
9890 for count is 1
[0. 1. 0.]
9891 for count is 2
[0. 0. 1.]
9892 for count is 1
[0. 1. 0.]
9893 for count is 1
[0. 1. 0.]
9894 for count is 2
[0. 0. 1.]
9895 for count is 1
[0. 1. 0.]
9896 for count is 2
[0. 0. 1.]
9897 for count is 2
[0. 0. 1.]
9898 for count is 2
[0. 0. 1.]
9899 for count is 0
[1. 0. 0.]
9900 for count is 1
[0. 1. 0.]
9901 for count is 2
[0. 0. 1.]
9902 for count is 2
[0. 0. 1.]
9903 for count is 1
[0. 1. 0

[0. 0. 1.]
10693 for count is 2
[0. 0. 1.]
10694 for count is 2
[0. 0. 1.]
10695 for count is 2
[0. 0. 1.]
10696 for count is 1
[0. 1. 0.]
10697 for count is 0
[1. 0. 0.]
10698 for count is 2
[0. 0. 1.]
10699 for count is 1
[0. 1. 0.]
10700 for count is 0
[1. 0. 0.]
10701 for count is 0
[1. 0. 0.]
10702 for count is 2
[0. 0. 1.]
10703 for count is 2
[0. 0. 1.]
10704 for count is 2
[0. 0. 1.]
10705 for count is 1
[0. 1. 0.]
10706 for count is 2
[0. 0. 1.]
10707 for count is 0
[1. 0. 0.]
10708 for count is 1
[0. 1. 0.]
10709 for count is 2
[0. 0. 1.]
10710 for count is 1
[0. 1. 0.]
10711 for count is 0
[1. 0. 0.]
10712 for count is 0
[1. 0. 0.]
10713 for count is 1
[0. 1. 0.]
10714 for count is 1
[0. 1. 0.]
10715 for count is 2
[0. 0. 1.]
10716 for count is 1
[0. 1. 0.]
10717 for count is 2
[0. 0. 1.]
10718 for count is 2
[0. 0. 1.]
10719 for count is 2
[0. 0. 1.]
10720 for count is 2
[0. 0. 1.]
10721 for count is 2
[0. 0. 1.]
10722 for count is 1
[0. 1. 0.]
10723 for count is 2
[0. 0. 1

[0. 1. 0.]
11368 for count is 2
[0. 0. 1.]
11369 for count is 1
[0. 1. 0.]
11370 for count is 0
[1. 0. 0.]
11371 for count is 2
[0. 0. 1.]
11372 for count is 2
[0. 0. 1.]
11373 for count is 2
[0. 0. 1.]
11374 for count is 2
[0. 0. 1.]
11375 for count is 1
[0. 1. 0.]
11376 for count is 1
[0. 1. 0.]
11377 for count is 1
[0. 1. 0.]
11378 for count is 2
[0. 0. 1.]
11379 for count is 1
[0. 1. 0.]
11380 for count is 0
[1. 0. 0.]
11381 for count is 2
[0. 0. 1.]
11382 for count is 0
[1. 0. 0.]
11383 for count is 1
[0. 1. 0.]
11384 for count is 1
[0. 1. 0.]
11385 for count is 1
[0. 1. 0.]
11386 for count is 1
[0. 1. 0.]
11387 for count is 1
[0. 1. 0.]
11388 for count is 1
[0. 1. 0.]
11389 for count is 1
[0. 1. 0.]
11390 for count is 1
[0. 1. 0.]
11391 for count is 0
[1. 0. 0.]
11392 for count is 2
[0. 0. 1.]
11393 for count is 2
[0. 0. 1.]
11394 for count is 0
[1. 0. 0.]
11395 for count is 2
[0. 0. 1.]
11396 for count is 0
[1. 0. 0.]
11397 for count is 2
[0. 0. 1.]
11398 for count is 2
[0. 0. 1

[0. 0. 1.]
12012 for count is 2
[0. 0. 1.]
12013 for count is 2
[0. 0. 1.]
12014 for count is 2
[0. 0. 1.]
12015 for count is 2
[0. 0. 1.]
12016 for count is 1
[0. 1. 0.]
12017 for count is 2
[0. 0. 1.]
12018 for count is 1
[0. 1. 0.]
12019 for count is 0
[1. 0. 0.]
12020 for count is 2
[0. 0. 1.]
12021 for count is 2
[0. 0. 1.]
12022 for count is 0
[1. 0. 0.]
12023 for count is 1
[0. 1. 0.]
12024 for count is 2
[0. 0. 1.]
12025 for count is 2
[0. 0. 1.]
12026 for count is 2
[0. 0. 1.]
12027 for count is 2
[0. 0. 1.]
12028 for count is 2
[0. 0. 1.]
12029 for count is 1
[0. 1. 0.]
12030 for count is 2
[0. 0. 1.]
12031 for count is 1
[0. 1. 0.]
12032 for count is 2
[0. 0. 1.]
12033 for count is 2
[0. 0. 1.]
12034 for count is 1
[0. 1. 0.]
12035 for count is 1
[0. 1. 0.]
12036 for count is 1
[0. 1. 0.]
12037 for count is 0
[1. 0. 0.]
12038 for count is 2
[0. 0. 1.]
12039 for count is 2
[0. 0. 1.]
12040 for count is 2
[0. 0. 1.]
12041 for count is 0
[1. 0. 0.]
12042 for count is 1
[0. 1. 0

[0. 0. 1.]
12763 for count is 0
[1. 0. 0.]
12764 for count is 1
[0. 1. 0.]
12765 for count is 0
[1. 0. 0.]
12766 for count is 1
[0. 1. 0.]
12767 for count is 2
[0. 0. 1.]
12768 for count is 0
[1. 0. 0.]
12769 for count is 2
[0. 0. 1.]
12770 for count is 0
[1. 0. 0.]
12771 for count is 2
[0. 0. 1.]
12772 for count is 1
[0. 1. 0.]
12773 for count is 1
[0. 1. 0.]
12774 for count is 2
[0. 0. 1.]
12775 for count is 2
[0. 0. 1.]
12776 for count is 2
[0. 0. 1.]
12777 for count is 2
[0. 0. 1.]
12778 for count is 1
[0. 1. 0.]
12779 for count is 2
[0. 0. 1.]
12780 for count is 0
[1. 0. 0.]
12781 for count is 2
[0. 0. 1.]
12782 for count is 2
[0. 0. 1.]
12783 for count is 2
[0. 0. 1.]
12784 for count is 2
[0. 0. 1.]
12785 for count is 0
[1. 0. 0.]
12786 for count is 2
[0. 0. 1.]
12787 for count is 0
[1. 0. 0.]
12788 for count is 1
[0. 1. 0.]
12789 for count is 2
[0. 0. 1.]
12790 for count is 2
[0. 0. 1.]
12791 for count is 0
[1. 0. 0.]
12792 for count is 2
[0. 0. 1.]
12793 for count is 0
[1. 0. 0

[0. 1. 0.]
13506 for count is 2
[0. 0. 1.]
13507 for count is 1
[0. 1. 0.]
13508 for count is 2
[0. 0. 1.]
13509 for count is 1
[0. 1. 0.]
13510 for count is 2
[0. 0. 1.]
13511 for count is 2
[0. 0. 1.]
13512 for count is 2
[0. 0. 1.]
13513 for count is 2
[0. 0. 1.]
13514 for count is 1
[0. 1. 0.]
13515 for count is 1
[0. 1. 0.]
13516 for count is 2
[0. 0. 1.]
13517 for count is 2
[0. 0. 1.]
13518 for count is 0
[1. 0. 0.]
13519 for count is 2
[0. 0. 1.]
13520 for count is 1
[0. 1. 0.]
13521 for count is 2
[0. 0. 1.]
13522 for count is 1
[0. 1. 0.]
13523 for count is 0
[1. 0. 0.]
13524 for count is 1
[0. 1. 0.]
13525 for count is 0
[1. 0. 0.]
13526 for count is 0
[1. 0. 0.]
13527 for count is 0
[1. 0. 0.]
13528 for count is 1
[0. 1. 0.]
13529 for count is 1
[0. 1. 0.]
13530 for count is 0
[1. 0. 0.]
13531 for count is 1
[0. 1. 0.]
13532 for count is 1
[0. 1. 0.]
13533 for count is 2
[0. 0. 1.]
13534 for count is 0
[1. 0. 0.]
13535 for count is 0
[1. 0. 0.]
13536 for count is 1
[0. 1. 0

[1. 0. 0.]
14229 for count is 0
[1. 0. 0.]
14230 for count is 1
[0. 1. 0.]
14231 for count is 2
[0. 0. 1.]
14232 for count is 2
[0. 0. 1.]
14233 for count is 2
[0. 0. 1.]
14234 for count is 1
[0. 1. 0.]
14235 for count is 2
[0. 0. 1.]
14236 for count is 1
[0. 1. 0.]
14237 for count is 1
[0. 1. 0.]
14238 for count is 2
[0. 0. 1.]
14239 for count is 1
[0. 1. 0.]
14240 for count is 2
[0. 0. 1.]
14241 for count is 2
[0. 0. 1.]
14242 for count is 0
[1. 0. 0.]
14243 for count is 2
[0. 0. 1.]
14244 for count is 2
[0. 0. 1.]
14245 for count is 2
[0. 0. 1.]
14246 for count is 0
[1. 0. 0.]
14247 for count is 1
[0. 1. 0.]
14248 for count is 2
[0. 0. 1.]
14249 for count is 2
[0. 0. 1.]
14250 for count is 1
[0. 1. 0.]
14251 for count is 0
[1. 0. 0.]
14252 for count is 0
[1. 0. 0.]
14253 for count is 0
[1. 0. 0.]
14254 for count is 0
[1. 0. 0.]
14255 for count is 2
[0. 0. 1.]
14256 for count is 1
[0. 1. 0.]
14257 for count is 1
[0. 1. 0.]
14258 for count is 2
[0. 0. 1.]
14259 for count is 0
[1. 0. 0

[0. 0. 1.]
14863 for count is 0
[1. 0. 0.]
14864 for count is 2
[0. 0. 1.]
14865 for count is 2
[0. 0. 1.]
14866 for count is 0
[1. 0. 0.]
14867 for count is 1
[0. 1. 0.]
14868 for count is 2
[0. 0. 1.]
14869 for count is 2
[0. 0. 1.]
14870 for count is 1
[0. 1. 0.]
14871 for count is 2
[0. 0. 1.]
14872 for count is 2
[0. 0. 1.]
14873 for count is 0
[1. 0. 0.]
14874 for count is 1
[0. 1. 0.]
14875 for count is 1
[0. 1. 0.]
14876 for count is 2
[0. 0. 1.]
14877 for count is 2
[0. 0. 1.]
14878 for count is 2
[0. 0. 1.]
14879 for count is 2
[0. 0. 1.]
14880 for count is 2
[0. 0. 1.]
14881 for count is 2
[0. 0. 1.]
14882 for count is 1
[0. 1. 0.]
14883 for count is 1
[0. 1. 0.]
14884 for count is 1
[0. 1. 0.]
14885 for count is 1
[0. 1. 0.]
14886 for count is 2
[0. 0. 1.]
14887 for count is 1
[0. 1. 0.]
14888 for count is 1
[0. 1. 0.]
14889 for count is 1
[0. 1. 0.]
14890 for count is 1
[0. 1. 0.]
14891 for count is 0
[1. 0. 0.]
14892 for count is 2
[0. 0. 1.]
14893 for count is 2
[0. 0. 1

[0. 1. 0.]
15548 for count is 0
[1. 0. 0.]
15549 for count is 2
[0. 0. 1.]
15550 for count is 2
[0. 0. 1.]
15551 for count is 0
[1. 0. 0.]
15552 for count is 1
[0. 1. 0.]
15553 for count is 0
[1. 0. 0.]
15554 for count is 0
[1. 0. 0.]
15555 for count is 1
[0. 1. 0.]
15556 for count is 2
[0. 0. 1.]
15557 for count is 2
[0. 0. 1.]
15558 for count is 1
[0. 1. 0.]
15559 for count is 2
[0. 0. 1.]
15560 for count is 0
[1. 0. 0.]
15561 for count is 2
[0. 0. 1.]
15562 for count is 2
[0. 0. 1.]
15563 for count is 2
[0. 0. 1.]
15564 for count is 1
[0. 1. 0.]
15565 for count is 0
[1. 0. 0.]
15566 for count is 0
[1. 0. 0.]
15567 for count is 1
[0. 1. 0.]
15568 for count is 1
[0. 1. 0.]
15569 for count is 0
[1. 0. 0.]
15570 for count is 2
[0. 0. 1.]
15571 for count is 1
[0. 1. 0.]
15572 for count is 1
[0. 1. 0.]
15573 for count is 2
[0. 0. 1.]
15574 for count is 2
[0. 0. 1.]
15575 for count is 1
[0. 1. 0.]
15576 for count is 1
[0. 1. 0.]
15577 for count is 0
[1. 0. 0.]
15578 for count is 1
[0. 1. 0

[1. 0. 0.]
16235 for count is 1
[0. 1. 0.]
16236 for count is 2
[0. 0. 1.]
16237 for count is 2
[0. 0. 1.]
16238 for count is 2
[0. 0. 1.]
16239 for count is 1
[0. 1. 0.]
16240 for count is 1
[0. 1. 0.]
16241 for count is 2
[0. 0. 1.]
16242 for count is 2
[0. 0. 1.]
16243 for count is 2
[0. 0. 1.]
16244 for count is 2
[0. 0. 1.]
16245 for count is 2
[0. 0. 1.]
16246 for count is 1
[0. 1. 0.]
16247 for count is 1
[0. 1. 0.]
16248 for count is 0
[1. 0. 0.]
16249 for count is 2
[0. 0. 1.]
16250 for count is 1
[0. 1. 0.]
16251 for count is 2
[0. 0. 1.]
16252 for count is 2
[0. 0. 1.]
16253 for count is 2
[0. 0. 1.]
16254 for count is 2
[0. 0. 1.]
16255 for count is 2
[0. 0. 1.]
16256 for count is 2
[0. 0. 1.]
16257 for count is 0
[1. 0. 0.]
16258 for count is 2
[0. 0. 1.]
16259 for count is 1
[0. 1. 0.]
16260 for count is 0
[1. 0. 0.]
16261 for count is 1
[0. 1. 0.]
16262 for count is 1
[0. 1. 0.]
16263 for count is 1
[0. 1. 0.]
16264 for count is 2
[0. 0. 1.]
16265 for count is 2
[0. 0. 1

[0. 0. 1.]
16976 for count is 2
[0. 0. 1.]
16977 for count is 1
[0. 1. 0.]
16978 for count is 2
[0. 0. 1.]
16979 for count is 2
[0. 0. 1.]
16980 for count is 1
[0. 1. 0.]
16981 for count is 2
[0. 0. 1.]
16982 for count is 2
[0. 0. 1.]
16983 for count is 0
[1. 0. 0.]
16984 for count is 1
[0. 1. 0.]
16985 for count is 1
[0. 1. 0.]
16986 for count is 1
[0. 1. 0.]
16987 for count is 1
[0. 1. 0.]
16988 for count is 2
[0. 0. 1.]
16989 for count is 2
[0. 0. 1.]
16990 for count is 2
[0. 0. 1.]
16991 for count is 0
[1. 0. 0.]
16992 for count is 1
[0. 1. 0.]
16993 for count is 1
[0. 1. 0.]
16994 for count is 1
[0. 1. 0.]
16995 for count is 0
[1. 0. 0.]
16996 for count is 2
[0. 0. 1.]
16997 for count is 2
[0. 0. 1.]
16998 for count is 2
[0. 0. 1.]
16999 for count is 2
[0. 0. 1.]
17000 for count is 1
[0. 1. 0.]
17001 for count is 2
[0. 0. 1.]
17002 for count is 1
[0. 1. 0.]
17003 for count is 2
[0. 0. 1.]
17004 for count is 2
[0. 0. 1.]
17005 for count is 2
[0. 0. 1.]
17006 for count is 1
[0. 1. 0

[0. 1. 0.]
17685 for count is 2
[0. 0. 1.]
17686 for count is 2
[0. 0. 1.]
17687 for count is 1
[0. 1. 0.]
17688 for count is 1
[0. 1. 0.]
17689 for count is 2
[0. 0. 1.]
17690 for count is 1
[0. 1. 0.]
17691 for count is 2
[0. 0. 1.]
17692 for count is 2
[0. 0. 1.]
17693 for count is 2
[0. 0. 1.]
17694 for count is 1
[0. 1. 0.]
17695 for count is 2
[0. 0. 1.]
17696 for count is 2
[0. 0. 1.]
17697 for count is 2
[0. 0. 1.]
17698 for count is 0
[1. 0. 0.]
17699 for count is 0
[1. 0. 0.]
17700 for count is 2
[0. 0. 1.]
17701 for count is 2
[0. 0. 1.]
17702 for count is 1
[0. 1. 0.]
17703 for count is 2
[0. 0. 1.]
17704 for count is 0
[1. 0. 0.]
17705 for count is 0
[1. 0. 0.]
17706 for count is 0
[1. 0. 0.]
17707 for count is 1
[0. 1. 0.]
17708 for count is 1
[0. 1. 0.]
17709 for count is 2
[0. 0. 1.]
17710 for count is 2
[0. 0. 1.]
17711 for count is 0
[1. 0. 0.]
17712 for count is 1
[0. 1. 0.]
17713 for count is 1
[0. 1. 0.]
17714 for count is 2
[0. 0. 1.]
17715 for count is 2
[0. 0. 1

[0. 1. 0.]
18171 for count is 2
[0. 0. 1.]
18172 for count is 1
[0. 1. 0.]
18173 for count is 2
[0. 0. 1.]
18174 for count is 0
[1. 0. 0.]
18175 for count is 1
[0. 1. 0.]
18176 for count is 1
[0. 1. 0.]
18177 for count is 1
[0. 1. 0.]
18178 for count is 2
[0. 0. 1.]
18179 for count is 2
[0. 0. 1.]
18180 for count is 2
[0. 0. 1.]
18181 for count is 2
[0. 0. 1.]
18182 for count is 1
[0. 1. 0.]
18183 for count is 2
[0. 0. 1.]
18184 for count is 2
[0. 0. 1.]
18185 for count is 2
[0. 0. 1.]
18186 for count is 2
[0. 0. 1.]
18187 for count is 1
[0. 1. 0.]
18188 for count is 2
[0. 0. 1.]
18189 for count is 2
[0. 0. 1.]
18190 for count is 2
[0. 0. 1.]
18191 for count is 2
[0. 0. 1.]
18192 for count is 1
[0. 1. 0.]
18193 for count is 0
[1. 0. 0.]
18194 for count is 2
[0. 0. 1.]
18195 for count is 0
[1. 0. 0.]
18196 for count is 2
[0. 0. 1.]
18197 for count is 1
[0. 1. 0.]
18198 for count is 1
[0. 1. 0.]
18199 for count is 1
[0. 1. 0.]
18200 for count is 2
[0. 0. 1.]
18201 for count is 2
[0. 0. 1

[0. 0. 1.]
18901 for count is 2
[0. 0. 1.]
18902 for count is 2
[0. 0. 1.]
18903 for count is 2
[0. 0. 1.]
18904 for count is 0
[1. 0. 0.]
18905 for count is 2
[0. 0. 1.]
18906 for count is 1
[0. 1. 0.]
18907 for count is 0
[1. 0. 0.]
18908 for count is 2
[0. 0. 1.]
18909 for count is 2
[0. 0. 1.]
18910 for count is 1
[0. 1. 0.]
18911 for count is 0
[1. 0. 0.]
18912 for count is 2
[0. 0. 1.]
18913 for count is 0
[1. 0. 0.]
18914 for count is 1
[0. 1. 0.]
18915 for count is 2
[0. 0. 1.]
18916 for count is 1
[0. 1. 0.]
18917 for count is 0
[1. 0. 0.]
18918 for count is 2
[0. 0. 1.]
18919 for count is 2
[0. 0. 1.]
18920 for count is 1
[0. 1. 0.]
18921 for count is 1
[0. 1. 0.]
18922 for count is 2
[0. 0. 1.]
18923 for count is 1
[0. 1. 0.]
18924 for count is 0
[1. 0. 0.]
18925 for count is 2
[0. 0. 1.]
18926 for count is 1
[0. 1. 0.]
18927 for count is 0
[1. 0. 0.]
18928 for count is 1
[0. 1. 0.]
18929 for count is 1
[0. 1. 0.]
18930 for count is 2
[0. 0. 1.]
18931 for count is 0
[1. 0. 0

[1. 0. 0.]
19530 for count is 2
[0. 0. 1.]
19531 for count is 1
[0. 1. 0.]
19532 for count is 2
[0. 0. 1.]
19533 for count is 1
[0. 1. 0.]
19534 for count is 1
[0. 1. 0.]
19535 for count is 2
[0. 0. 1.]
19536 for count is 2
[0. 0. 1.]
19537 for count is 0
[1. 0. 0.]
19538 for count is 1
[0. 1. 0.]
19539 for count is 1
[0. 1. 0.]
19540 for count is 0
[1. 0. 0.]
19541 for count is 1
[0. 1. 0.]
19542 for count is 0
[1. 0. 0.]
19543 for count is 1
[0. 1. 0.]
19544 for count is 2
[0. 0. 1.]
19545 for count is 2
[0. 0. 1.]
19546 for count is 0
[1. 0. 0.]
19547 for count is 1
[0. 1. 0.]
19548 for count is 2
[0. 0. 1.]
19549 for count is 1
[0. 1. 0.]
19550 for count is 1
[0. 1. 0.]
19551 for count is 2
[0. 0. 1.]
19552 for count is 2
[0. 0. 1.]
19553 for count is 1
[0. 1. 0.]
19554 for count is 1
[0. 1. 0.]
19555 for count is 1
[0. 1. 0.]
19556 for count is 1
[0. 1. 0.]
19557 for count is 2
[0. 0. 1.]
19558 for count is 2
[0. 0. 1.]
19559 for count is 0
[1. 0. 0.]
19560 for count is 2
[0. 0. 1

[1. 0. 0.]
20729 for count is 2
[0. 0. 1.]
20730 for count is 1
[0. 1. 0.]
20731 for count is 1
[0. 1. 0.]
20732 for count is 2
[0. 0. 1.]
20733 for count is 2
[0. 0. 1.]
20734 for count is 0
[1. 0. 0.]
20735 for count is 1
[0. 1. 0.]
20736 for count is 1
[0. 1. 0.]
20737 for count is 2
[0. 0. 1.]
20738 for count is 0
[1. 0. 0.]
20739 for count is 0
[1. 0. 0.]
20740 for count is 0
[1. 0. 0.]
20741 for count is 2
[0. 0. 1.]
20742 for count is 2
[0. 0. 1.]
20743 for count is 2
[0. 0. 1.]
20744 for count is 2
[0. 0. 1.]
20745 for count is 1
[0. 1. 0.]
20746 for count is 0
[1. 0. 0.]
20747 for count is 1
[0. 1. 0.]
20748 for count is 2
[0. 0. 1.]
20749 for count is 2
[0. 0. 1.]
20750 for count is 0
[1. 0. 0.]
20751 for count is 2
[0. 0. 1.]
20752 for count is 1
[0. 1. 0.]
20753 for count is 0
[1. 0. 0.]
20754 for count is 0
[1. 0. 0.]
20755 for count is 1
[0. 1. 0.]
20756 for count is 2
[0. 0. 1.]
20757 for count is 1
[0. 1. 0.]
20758 for count is 0
[1. 0. 0.]
20759 for count is 1
[0. 1. 0

[0. 0. 1.]
21422 for count is 1
[0. 1. 0.]
21423 for count is 2
[0. 0. 1.]
21424 for count is 0
[1. 0. 0.]
21425 for count is 2
[0. 0. 1.]
21426 for count is 0
[1. 0. 0.]
21427 for count is 0
[1. 0. 0.]
21428 for count is 2
[0. 0. 1.]
21429 for count is 2
[0. 0. 1.]
21430 for count is 2
[0. 0. 1.]
21431 for count is 2
[0. 0. 1.]
21432 for count is 2
[0. 0. 1.]
21433 for count is 2
[0. 0. 1.]
21434 for count is 1
[0. 1. 0.]
21435 for count is 1
[0. 1. 0.]
21436 for count is 2
[0. 0. 1.]
21437 for count is 2
[0. 0. 1.]
21438 for count is 2
[0. 0. 1.]
21439 for count is 2
[0. 0. 1.]
21440 for count is 2
[0. 0. 1.]
21441 for count is 2
[0. 0. 1.]
21442 for count is 1
[0. 1. 0.]
21443 for count is 0
[1. 0. 0.]
21444 for count is 1
[0. 1. 0.]
21445 for count is 0
[1. 0. 0.]
21446 for count is 2
[0. 0. 1.]
21447 for count is 2
[0. 0. 1.]
21448 for count is 1
[0. 1. 0.]
21449 for count is 2
[0. 0. 1.]
21450 for count is 1
[0. 1. 0.]
21451 for count is 2
[0. 0. 1.]
21452 for count is 2
[0. 0. 1

[0. 1. 0.]
22145 for count is 0
[1. 0. 0.]
22146 for count is 1
[0. 1. 0.]
22147 for count is 2
[0. 0. 1.]
22148 for count is 2
[0. 0. 1.]
22149 for count is 2
[0. 0. 1.]
22150 for count is 2
[0. 0. 1.]
22151 for count is 2
[0. 0. 1.]
22152 for count is 2
[0. 0. 1.]
22153 for count is 2
[0. 0. 1.]
22154 for count is 0
[1. 0. 0.]
22155 for count is 2
[0. 0. 1.]
22156 for count is 2
[0. 0. 1.]
22157 for count is 1
[0. 1. 0.]
22158 for count is 2
[0. 0. 1.]
22159 for count is 1
[0. 1. 0.]
22160 for count is 1
[0. 1. 0.]
22161 for count is 2
[0. 0. 1.]
22162 for count is 2
[0. 0. 1.]
22163 for count is 1
[0. 1. 0.]
22164 for count is 2
[0. 0. 1.]
22165 for count is 2
[0. 0. 1.]
22166 for count is 1
[0. 1. 0.]
22167 for count is 0
[1. 0. 0.]
22168 for count is 2
[0. 0. 1.]
22169 for count is 2
[0. 0. 1.]
22170 for count is 2
[0. 0. 1.]
22171 for count is 2
[0. 0. 1.]
22172 for count is 1
[0. 1. 0.]
22173 for count is 2
[0. 0. 1.]
22174 for count is 1
[0. 1. 0.]
22175 for count is 1
[0. 1. 0

[0. 0. 1.]
22842 for count is 1
[0. 1. 0.]
22843 for count is 2
[0. 0. 1.]
22844 for count is 1
[0. 1. 0.]
22845 for count is 1
[0. 1. 0.]
22846 for count is 2
[0. 0. 1.]
22847 for count is 0
[1. 0. 0.]
22848 for count is 2
[0. 0. 1.]
22849 for count is 1
[0. 1. 0.]
22850 for count is 0
[1. 0. 0.]
22851 for count is 2
[0. 0. 1.]
22852 for count is 0
[1. 0. 0.]
22853 for count is 2
[0. 0. 1.]
22854 for count is 2
[0. 0. 1.]
22855 for count is 2
[0. 0. 1.]
22856 for count is 0
[1. 0. 0.]
22857 for count is 1
[0. 1. 0.]
22858 for count is 1
[0. 1. 0.]
22859 for count is 2
[0. 0. 1.]
22860 for count is 2
[0. 0. 1.]
22861 for count is 0
[1. 0. 0.]
22862 for count is 0
[1. 0. 0.]
22863 for count is 2
[0. 0. 1.]
22864 for count is 2
[0. 0. 1.]
22865 for count is 1
[0. 1. 0.]
22866 for count is 1
[0. 1. 0.]
22867 for count is 1
[0. 1. 0.]
22868 for count is 1
[0. 1. 0.]
22869 for count is 2
[0. 0. 1.]
22870 for count is 0
[1. 0. 0.]
22871 for count is 0
[1. 0. 0.]
22872 for count is 1
[0. 1. 0

[0. 0. 1.]
23511 for count is 1
[0. 1. 0.]
23512 for count is 2
[0. 0. 1.]
23513 for count is 2
[0. 0. 1.]
23514 for count is 1
[0. 1. 0.]
23515 for count is 1
[0. 1. 0.]
23516 for count is 1
[0. 1. 0.]
23517 for count is 0
[1. 0. 0.]
23518 for count is 2
[0. 0. 1.]
23519 for count is 0
[1. 0. 0.]
23520 for count is 2
[0. 0. 1.]
23521 for count is 2
[0. 0. 1.]
23522 for count is 2
[0. 0. 1.]
23523 for count is 2
[0. 0. 1.]
23524 for count is 2
[0. 0. 1.]
23525 for count is 2
[0. 0. 1.]
23526 for count is 1
[0. 1. 0.]
23527 for count is 2
[0. 0. 1.]
23528 for count is 2
[0. 0. 1.]
23529 for count is 2
[0. 0. 1.]
23530 for count is 1
[0. 1. 0.]
23531 for count is 2
[0. 0. 1.]
23532 for count is 1
[0. 1. 0.]
23533 for count is 2
[0. 0. 1.]
23534 for count is 1
[0. 1. 0.]
23535 for count is 0
[1. 0. 0.]
23536 for count is 1
[0. 1. 0.]
23537 for count is 2
[0. 0. 1.]
23538 for count is 2
[0. 0. 1.]
23539 for count is 2
[0. 0. 1.]
23540 for count is 2
[0. 0. 1.]
23541 for count is 2
[0. 0. 1

[0. 0. 1.]
24293 for count is 2
[0. 0. 1.]
24294 for count is 2
[0. 0. 1.]
24295 for count is 0
[1. 0. 0.]
24296 for count is 1
[0. 1. 0.]
24297 for count is 0
[1. 0. 0.]
24298 for count is 1
[0. 1. 0.]
24299 for count is 2
[0. 0. 1.]
24300 for count is 1
[0. 1. 0.]
24301 for count is 2
[0. 0. 1.]
24302 for count is 2
[0. 0. 1.]
24303 for count is 2
[0. 0. 1.]
24304 for count is 2
[0. 0. 1.]
24305 for count is 2
[0. 0. 1.]
24306 for count is 1
[0. 1. 0.]
24307 for count is 2
[0. 0. 1.]
24308 for count is 2
[0. 0. 1.]
24309 for count is 1
[0. 1. 0.]
24310 for count is 2
[0. 0. 1.]
24311 for count is 0
[1. 0. 0.]
24312 for count is 1
[0. 1. 0.]
24313 for count is 2
[0. 0. 1.]
24314 for count is 1
[0. 1. 0.]
24315 for count is 2
[0. 0. 1.]
24316 for count is 2
[0. 0. 1.]
24317 for count is 0
[1. 0. 0.]
24318 for count is 2
[0. 0. 1.]
24319 for count is 1
[0. 1. 0.]
24320 for count is 0
[1. 0. 0.]
24321 for count is 1
[0. 1. 0.]
24322 for count is 2
[0. 0. 1.]
24323 for count is 0
[1. 0. 0

[0. 0. 1.]
25023 for count is 1
[0. 1. 0.]
25024 for count is 0
[1. 0. 0.]
25025 for count is 0
[1. 0. 0.]
25026 for count is 1
[0. 1. 0.]
25027 for count is 2
[0. 0. 1.]
25028 for count is 2
[0. 0. 1.]
25029 for count is 1
[0. 1. 0.]
25030 for count is 2
[0. 0. 1.]
25031 for count is 1
[0. 1. 0.]
25032 for count is 0
[1. 0. 0.]
25033 for count is 2
[0. 0. 1.]
25034 for count is 2
[0. 0. 1.]
25035 for count is 2
[0. 0. 1.]
25036 for count is 0
[1. 0. 0.]
25037 for count is 1
[0. 1. 0.]
25038 for count is 2
[0. 0. 1.]
25039 for count is 0
[1. 0. 0.]
25040 for count is 1
[0. 1. 0.]
25041 for count is 1
[0. 1. 0.]
25042 for count is 2
[0. 0. 1.]
25043 for count is 2
[0. 0. 1.]
25044 for count is 2
[0. 0. 1.]
25045 for count is 2
[0. 0. 1.]
25046 for count is 1
[0. 1. 0.]
25047 for count is 1
[0. 1. 0.]
25048 for count is 2
[0. 0. 1.]
25049 for count is 0
[1. 0. 0.]
25050 for count is 1
[0. 1. 0.]
25051 for count is 2
[0. 0. 1.]
25052 for count is 1
[0. 1. 0.]
25053 for count is 2
[0. 0. 1

25724 for count is 0
[1. 0. 0.]
25725 for count is 1
[0. 1. 0.]
25726 for count is 2
[0. 0. 1.]
25727 for count is 1
[0. 1. 0.]
25728 for count is 2
[0. 0. 1.]
25729 for count is 2
[0. 0. 1.]
25730 for count is 1
[0. 1. 0.]
25731 for count is 0
[1. 0. 0.]
25732 for count is 2
[0. 0. 1.]
25733 for count is 1
[0. 1. 0.]
25734 for count is 2
[0. 0. 1.]
25735 for count is 1
[0. 1. 0.]
25736 for count is 1
[0. 1. 0.]
25737 for count is 2
[0. 0. 1.]
25738 for count is 0
[1. 0. 0.]
25739 for count is 2
[0. 0. 1.]
25740 for count is 2
[0. 0. 1.]
25741 for count is 1
[0. 1. 0.]
25742 for count is 2
[0. 0. 1.]
25743 for count is 0
[1. 0. 0.]
25744 for count is 2
[0. 0. 1.]
25745 for count is 2
[0. 0. 1.]
25746 for count is 1
[0. 1. 0.]
25747 for count is 2
[0. 0. 1.]
25748 for count is 2
[0. 0. 1.]
25749 for count is 2
[0. 0. 1.]
25750 for count is 2
[0. 0. 1.]
25751 for count is 2
[0. 0. 1.]
25752 for count is 2
[0. 0. 1.]
25753 for count is 1
[0. 1. 0.]
25754 for count is 2
[0. 0. 1.]
25755 fo

[0. 1. 0.]
26379 for count is 2
[0. 0. 1.]
26380 for count is 1
[0. 1. 0.]
26381 for count is 2
[0. 0. 1.]
26382 for count is 2
[0. 0. 1.]
26383 for count is 2
[0. 0. 1.]
26384 for count is 0
[1. 0. 0.]
26385 for count is 2
[0. 0. 1.]
26386 for count is 1
[0. 1. 0.]
26387 for count is 1
[0. 1. 0.]
26388 for count is 2
[0. 0. 1.]
26389 for count is 2
[0. 0. 1.]
26390 for count is 2
[0. 0. 1.]
26391 for count is 1
[0. 1. 0.]
26392 for count is 0
[1. 0. 0.]
26393 for count is 2
[0. 0. 1.]
26394 for count is 1
[0. 1. 0.]
26395 for count is 0
[1. 0. 0.]
26396 for count is 2
[0. 0. 1.]
26397 for count is 2
[0. 0. 1.]
26398 for count is 1
[0. 1. 0.]
26399 for count is 2
[0. 0. 1.]
26400 for count is 0
[1. 0. 0.]
26401 for count is 1
[0. 1. 0.]
26402 for count is 2
[0. 0. 1.]
26403 for count is 2
[0. 0. 1.]
26404 for count is 0
[1. 0. 0.]
26405 for count is 1
[0. 1. 0.]
26406 for count is 1
[0. 1. 0.]
26407 for count is 2
[0. 0. 1.]
26408 for count is 1
[0. 1. 0.]
26409 for count is 1
[0. 1. 0

[0. 1. 0.]
27286 for count is 2
[0. 0. 1.]
27287 for count is 0
[1. 0. 0.]
27288 for count is 2
[0. 0. 1.]
27289 for count is 0
[1. 0. 0.]
27290 for count is 2
[0. 0. 1.]
27291 for count is 0
[1. 0. 0.]
27292 for count is 1
[0. 1. 0.]
27293 for count is 0
[1. 0. 0.]
27294 for count is 1
[0. 1. 0.]
27295 for count is 2
[0. 0. 1.]
27296 for count is 2
[0. 0. 1.]
27297 for count is 0
[1. 0. 0.]
27298 for count is 2
[0. 0. 1.]
27299 for count is 0
[1. 0. 0.]
27300 for count is 1
[0. 1. 0.]
27301 for count is 2
[0. 0. 1.]
27302 for count is 1
[0. 1. 0.]
27303 for count is 2
[0. 0. 1.]
27304 for count is 1
[0. 1. 0.]
27305 for count is 2
[0. 0. 1.]
27306 for count is 0
[1. 0. 0.]
27307 for count is 2
[0. 0. 1.]
27308 for count is 1
[0. 1. 0.]
27309 for count is 0
[1. 0. 0.]
27310 for count is 2
[0. 0. 1.]
27311 for count is 1
[0. 1. 0.]
27312 for count is 1
[0. 1. 0.]
27313 for count is 2
[0. 0. 1.]
27314 for count is 2
[0. 0. 1.]
27315 for count is 0
[1. 0. 0.]
27316 for count is 2
[0. 0. 1

[0. 1. 0.]
27951 for count is 2
[0. 0. 1.]
27952 for count is 1
[0. 1. 0.]
27953 for count is 2
[0. 0. 1.]
27954 for count is 2
[0. 0. 1.]
27955 for count is 2
[0. 0. 1.]
27956 for count is 2
[0. 0. 1.]
27957 for count is 1
[0. 1. 0.]
27958 for count is 1
[0. 1. 0.]
27959 for count is 2
[0. 0. 1.]
27960 for count is 2
[0. 0. 1.]
27961 for count is 2
[0. 0. 1.]
27962 for count is 1
[0. 1. 0.]
27963 for count is 2
[0. 0. 1.]
27964 for count is 2
[0. 0. 1.]
27965 for count is 1
[0. 1. 0.]
27966 for count is 2
[0. 0. 1.]
27967 for count is 1
[0. 1. 0.]
27968 for count is 2
[0. 0. 1.]
27969 for count is 0
[1. 0. 0.]
27970 for count is 1
[0. 1. 0.]
27971 for count is 0
[1. 0. 0.]
27972 for count is 2
[0. 0. 1.]
27973 for count is 2
[0. 0. 1.]
27974 for count is 1
[0. 1. 0.]
27975 for count is 0
[1. 0. 0.]
27976 for count is 1
[0. 1. 0.]
27977 for count is 2
[0. 0. 1.]
27978 for count is 2
[0. 0. 1.]
27979 for count is 2
[0. 0. 1.]
27980 for count is 2
[0. 0. 1.]
27981 for count is 0
[1. 0. 0

[1. 0. 0.]
28792 for count is 2
[0. 0. 1.]
28793 for count is 1
[0. 1. 0.]
28794 for count is 0
[1. 0. 0.]
28795 for count is 2
[0. 0. 1.]
28796 for count is 2
[0. 0. 1.]
28797 for count is 1
[0. 1. 0.]
28798 for count is 1
[0. 1. 0.]
28799 for count is 0
[1. 0. 0.]
28800 for count is 1
[0. 1. 0.]
28801 for count is 1
[0. 1. 0.]
28802 for count is 0
[1. 0. 0.]
28803 for count is 1
[0. 1. 0.]
28804 for count is 0
[1. 0. 0.]
28805 for count is 2
[0. 0. 1.]
28806 for count is 1
[0. 1. 0.]
28807 for count is 2
[0. 0. 1.]
28808 for count is 2
[0. 0. 1.]
28809 for count is 1
[0. 1. 0.]
28810 for count is 2
[0. 0. 1.]
28811 for count is 2
[0. 0. 1.]
28812 for count is 2
[0. 0. 1.]
28813 for count is 0
[1. 0. 0.]
28814 for count is 0
[1. 0. 0.]
28815 for count is 2
[0. 0. 1.]
28816 for count is 2
[0. 0. 1.]
28817 for count is 0
[1. 0. 0.]
28818 for count is 0
[1. 0. 0.]
28819 for count is 2
[0. 0. 1.]
28820 for count is 2
[0. 0. 1.]
28821 for count is 2
[0. 0. 1.]
28822 for count is 2
[0. 0. 1

29398 for count is 2
[0. 0. 1.]
29399 for count is 0
[1. 0. 0.]
29400 for count is 1
[0. 1. 0.]
29401 for count is 2
[0. 0. 1.]
29402 for count is 0
[1. 0. 0.]
29403 for count is 2
[0. 0. 1.]
29404 for count is 1
[0. 1. 0.]
29405 for count is 2
[0. 0. 1.]
29406 for count is 1
[0. 1. 0.]
29407 for count is 0
[1. 0. 0.]
29408 for count is 2
[0. 0. 1.]
29409 for count is 1
[0. 1. 0.]
29410 for count is 2
[0. 0. 1.]
29411 for count is 2
[0. 0. 1.]
29412 for count is 2
[0. 0. 1.]
29413 for count is 1
[0. 1. 0.]
29414 for count is 2
[0. 0. 1.]
29415 for count is 0
[1. 0. 0.]
29416 for count is 2
[0. 0. 1.]
29417 for count is 1
[0. 1. 0.]
29418 for count is 2
[0. 0. 1.]
29419 for count is 2
[0. 0. 1.]
29420 for count is 2
[0. 0. 1.]
29421 for count is 2
[0. 0. 1.]
29422 for count is 2
[0. 0. 1.]
29423 for count is 2
[0. 0. 1.]
29424 for count is 1
[0. 1. 0.]
29425 for count is 2
[0. 0. 1.]
29426 for count is 2
[0. 0. 1.]
29427 for count is 0
[1. 0. 0.]
29428 for count is 2
[0. 0. 1.]
29429 fo

[1. 0. 0.]
30311 for count is 2
[0. 0. 1.]
30312 for count is 2
[0. 0. 1.]
30313 for count is 1
[0. 1. 0.]
30314 for count is 0
[1. 0. 0.]
30315 for count is 0
[1. 0. 0.]
30316 for count is 2
[0. 0. 1.]
30317 for count is 2
[0. 0. 1.]
30318 for count is 1
[0. 1. 0.]
30319 for count is 2
[0. 0. 1.]
30320 for count is 1
[0. 1. 0.]
30321 for count is 2
[0. 0. 1.]
30322 for count is 0
[1. 0. 0.]
30323 for count is 1
[0. 1. 0.]
30324 for count is 2
[0. 0. 1.]
30325 for count is 2
[0. 0. 1.]
30326 for count is 1
[0. 1. 0.]
30327 for count is 2
[0. 0. 1.]
30328 for count is 2
[0. 0. 1.]
30329 for count is 1
[0. 1. 0.]
30330 for count is 2
[0. 0. 1.]
30331 for count is 1
[0. 1. 0.]
30332 for count is 2
[0. 0. 1.]
30333 for count is 2
[0. 0. 1.]
30334 for count is 0
[1. 0. 0.]
30335 for count is 2
[0. 0. 1.]
30336 for count is 2
[0. 0. 1.]
30337 for count is 0
[1. 0. 0.]
30338 for count is 1
[0. 1. 0.]
30339 for count is 2
[0. 0. 1.]
30340 for count is 2
[0. 0. 1.]
30341 for count is 2
[0. 0. 1

[0. 0. 1.]
30935 for count is 2
[0. 0. 1.]
30936 for count is 1
[0. 1. 0.]
30937 for count is 1
[0. 1. 0.]
30938 for count is 2
[0. 0. 1.]
30939 for count is 0
[1. 0. 0.]
30940 for count is 2
[0. 0. 1.]
30941 for count is 1
[0. 1. 0.]
30942 for count is 2
[0. 0. 1.]
30943 for count is 0
[1. 0. 0.]
30944 for count is 2
[0. 0. 1.]
30945 for count is 2
[0. 0. 1.]
30946 for count is 1
[0. 1. 0.]
30947 for count is 1
[0. 1. 0.]
30948 for count is 2
[0. 0. 1.]
30949 for count is 1
[0. 1. 0.]
30950 for count is 0
[1. 0. 0.]
30951 for count is 2
[0. 0. 1.]
30952 for count is 0
[1. 0. 0.]
30953 for count is 2
[0. 0. 1.]
30954 for count is 1
[0. 1. 0.]
30955 for count is 1
[0. 1. 0.]
30956 for count is 0
[1. 0. 0.]
30957 for count is 2
[0. 0. 1.]
30958 for count is 0
[1. 0. 0.]
30959 for count is 0
[1. 0. 0.]
30960 for count is 2
[0. 0. 1.]
30961 for count is 1
[0. 1. 0.]
30962 for count is 2
[0. 0. 1.]
30963 for count is 2
[0. 0. 1.]
30964 for count is 0
[1. 0. 0.]
30965 for count is 1
[0. 1. 0

[0. 1. 0.]
31821 for count is 0
[1. 0. 0.]
31822 for count is 0
[1. 0. 0.]
31823 for count is 0
[1. 0. 0.]
31824 for count is 2
[0. 0. 1.]
31825 for count is 0
[1. 0. 0.]
31826 for count is 0
[1. 0. 0.]
31827 for count is 2
[0. 0. 1.]
31828 for count is 1
[0. 1. 0.]
31829 for count is 0
[1. 0. 0.]
31830 for count is 1
[0. 1. 0.]
31831 for count is 2
[0. 0. 1.]
31832 for count is 1
[0. 1. 0.]
31833 for count is 1
[0. 1. 0.]
31834 for count is 0
[1. 0. 0.]
31835 for count is 0
[1. 0. 0.]
31836 for count is 0
[1. 0. 0.]
31837 for count is 1
[0. 1. 0.]
31838 for count is 2
[0. 0. 1.]
31839 for count is 0
[1. 0. 0.]
31840 for count is 1
[0. 1. 0.]
31841 for count is 0
[1. 0. 0.]
31842 for count is 1
[0. 1. 0.]
31843 for count is 1
[0. 1. 0.]
31844 for count is 2
[0. 0. 1.]
31845 for count is 2
[0. 0. 1.]
31846 for count is 2
[0. 0. 1.]
31847 for count is 1
[0. 1. 0.]
31848 for count is 2
[0. 0. 1.]
31849 for count is 1
[0. 1. 0.]
31850 for count is 2
[0. 0. 1.]
31851 for count is 2
[0. 0. 1

[0. 1. 0.]
32715 for count is 2
[0. 0. 1.]
32716 for count is 1
[0. 1. 0.]
32717 for count is 1
[0. 1. 0.]
32718 for count is 1
[0. 1. 0.]
32719 for count is 1
[0. 1. 0.]
32720 for count is 1
[0. 1. 0.]
32721 for count is 0
[1. 0. 0.]
32722 for count is 1
[0. 1. 0.]
32723 for count is 0
[1. 0. 0.]
32724 for count is 1
[0. 1. 0.]
32725 for count is 0
[1. 0. 0.]
32726 for count is 0
[1. 0. 0.]
32727 for count is 2
[0. 0. 1.]
32728 for count is 0
[1. 0. 0.]
32729 for count is 0
[1. 0. 0.]
32730 for count is 0
[1. 0. 0.]
32731 for count is 1
[0. 1. 0.]
32732 for count is 0
[1. 0. 0.]
32733 for count is 1
[0. 1. 0.]
32734 for count is 1
[0. 1. 0.]
32735 for count is 1
[0. 1. 0.]
32736 for count is 0
[1. 0. 0.]
32737 for count is 0
[1. 0. 0.]
32738 for count is 1
[0. 1. 0.]
32739 for count is 0
[1. 0. 0.]
32740 for count is 2
[0. 0. 1.]
32741 for count is 0
[1. 0. 0.]
32742 for count is 1
[0. 1. 0.]
32743 for count is 1
[0. 1. 0.]
32744 for count is 2
[0. 0. 1.]
32745 for count is 1
[0. 1. 0

[0. 1. 0.]
33538 for count is 2
[0. 0. 1.]
33539 for count is 1
[0. 1. 0.]
33540 for count is 1
[0. 1. 0.]
33541 for count is 1
[0. 1. 0.]
33542 for count is 2
[0. 0. 1.]
33543 for count is 2
[0. 0. 1.]
33544 for count is 1
[0. 1. 0.]
33545 for count is 1
[0. 1. 0.]
33546 for count is 2
[0. 0. 1.]
33547 for count is 1
[0. 1. 0.]
33548 for count is 2
[0. 0. 1.]
33549 for count is 1
[0. 1. 0.]
33550 for count is 1
[0. 1. 0.]
33551 for count is 2
[0. 0. 1.]
33552 for count is 0
[1. 0. 0.]
33553 for count is 1
[0. 1. 0.]
33554 for count is 1
[0. 1. 0.]
33555 for count is 0
[1. 0. 0.]
33556 for count is 1
[0. 1. 0.]
33557 for count is 2
[0. 0. 1.]
33558 for count is 2
[0. 0. 1.]
33559 for count is 2
[0. 0. 1.]
33560 for count is 1
[0. 1. 0.]
33561 for count is 1
[0. 1. 0.]
33562 for count is 2
[0. 0. 1.]
33563 for count is 2
[0. 0. 1.]
33564 for count is 1
[0. 1. 0.]
33565 for count is 1
[0. 1. 0.]
33566 for count is 1
[0. 1. 0.]
33567 for count is 2
[0. 0. 1.]
33568 for count is 1
[0. 1. 0

[0. 1. 0.]
34096 for count is 1
[0. 1. 0.]
34097 for count is 1
[0. 1. 0.]
34098 for count is 2
[0. 0. 1.]
34099 for count is 2
[0. 0. 1.]
34100 for count is 0
[1. 0. 0.]
34101 for count is 2
[0. 0. 1.]
34102 for count is 2
[0. 0. 1.]
34103 for count is 1
[0. 1. 0.]
34104 for count is 2
[0. 0. 1.]
34105 for count is 1
[0. 1. 0.]
34106 for count is 0
[1. 0. 0.]
34107 for count is 1
[0. 1. 0.]
34108 for count is 1
[0. 1. 0.]
34109 for count is 1
[0. 1. 0.]
34110 for count is 1
[0. 1. 0.]
34111 for count is 1
[0. 1. 0.]
34112 for count is 2
[0. 0. 1.]
34113 for count is 2
[0. 0. 1.]
34114 for count is 2
[0. 0. 1.]
34115 for count is 2
[0. 0. 1.]
34116 for count is 0
[1. 0. 0.]
34117 for count is 1
[0. 1. 0.]
34118 for count is 2
[0. 0. 1.]
34119 for count is 1
[0. 1. 0.]
34120 for count is 2
[0. 0. 1.]
34121 for count is 2
[0. 0. 1.]
34122 for count is 2
[0. 0. 1.]
34123 for count is 0
[1. 0. 0.]
34124 for count is 1
[0. 1. 0.]
34125 for count is 1
[0. 1. 0.]
34126 for count is 1
[0. 1. 0

[0. 1. 0.]
34945 for count is 2
[0. 0. 1.]
34946 for count is 1
[0. 1. 0.]
34947 for count is 1
[0. 1. 0.]
34948 for count is 2
[0. 0. 1.]
34949 for count is 1
[0. 1. 0.]
34950 for count is 1
[0. 1. 0.]
34951 for count is 2
[0. 0. 1.]
34952 for count is 2
[0. 0. 1.]
34953 for count is 2
[0. 0. 1.]
34954 for count is 2
[0. 0. 1.]
34955 for count is 1
[0. 1. 0.]
34956 for count is 2
[0. 0. 1.]
34957 for count is 2
[0. 0. 1.]
34958 for count is 0
[1. 0. 0.]
34959 for count is 1
[0. 1. 0.]
34960 for count is 0
[1. 0. 0.]
34961 for count is 1
[0. 1. 0.]
34962 for count is 2
[0. 0. 1.]
34963 for count is 1
[0. 1. 0.]
34964 for count is 1
[0. 1. 0.]
34965 for count is 1
[0. 1. 0.]
34966 for count is 2
[0. 0. 1.]
34967 for count is 1
[0. 1. 0.]
34968 for count is 0
[1. 0. 0.]
34969 for count is 1
[0. 1. 0.]
34970 for count is 2
[0. 0. 1.]
34971 for count is 1
[0. 1. 0.]
34972 for count is 1
[0. 1. 0.]
34973 for count is 2
[0. 0. 1.]
34974 for count is 2
[0. 0. 1.]
34975 for count is 0
[1. 0. 0

35684 for count is 0
[1. 0. 0.]
35685 for count is 1
[0. 1. 0.]
35686 for count is 0
[1. 0. 0.]
35687 for count is 0
[1. 0. 0.]
35688 for count is 1
[0. 1. 0.]
35689 for count is 0
[1. 0. 0.]
35690 for count is 0
[1. 0. 0.]
35691 for count is 2
[0. 0. 1.]
35692 for count is 1
[0. 1. 0.]
35693 for count is 1
[0. 1. 0.]
35694 for count is 2
[0. 0. 1.]
35695 for count is 0
[1. 0. 0.]
35696 for count is 2
[0. 0. 1.]
35697 for count is 2
[0. 0. 1.]
35698 for count is 2
[0. 0. 1.]
35699 for count is 1
[0. 1. 0.]
35700 for count is 2
[0. 0. 1.]
35701 for count is 0
[1. 0. 0.]
35702 for count is 0
[1. 0. 0.]
35703 for count is 2
[0. 0. 1.]
35704 for count is 2
[0. 0. 1.]
35705 for count is 1
[0. 1. 0.]
35706 for count is 2
[0. 0. 1.]
35707 for count is 1
[0. 1. 0.]
35708 for count is 0
[1. 0. 0.]
35709 for count is 0
[1. 0. 0.]
35710 for count is 2
[0. 0. 1.]
35711 for count is 2
[0. 0. 1.]
35712 for count is 1
[0. 1. 0.]
35713 for count is 1
[0. 1. 0.]
35714 for count is 0
[1. 0. 0.]
35715 fo

[0. 0. 1.]
36415 for count is 2
[0. 0. 1.]
36416 for count is 0
[1. 0. 0.]
36417 for count is 0
[1. 0. 0.]
36418 for count is 1
[0. 1. 0.]
36419 for count is 1
[0. 1. 0.]
36420 for count is 1
[0. 1. 0.]
36421 for count is 1
[0. 1. 0.]
36422 for count is 2
[0. 0. 1.]
36423 for count is 1
[0. 1. 0.]
36424 for count is 1
[0. 1. 0.]
36425 for count is 1
[0. 1. 0.]
36426 for count is 1
[0. 1. 0.]
36427 for count is 0
[1. 0. 0.]
36428 for count is 1
[0. 1. 0.]
36429 for count is 0
[1. 0. 0.]
36430 for count is 2
[0. 0. 1.]
36431 for count is 2
[0. 0. 1.]
36432 for count is 1
[0. 1. 0.]
36433 for count is 2
[0. 0. 1.]
36434 for count is 2
[0. 0. 1.]
36435 for count is 2
[0. 0. 1.]
36436 for count is 0
[1. 0. 0.]
36437 for count is 1
[0. 1. 0.]
36438 for count is 1
[0. 1. 0.]
36439 for count is 2
[0. 0. 1.]
36440 for count is 2
[0. 0. 1.]
36441 for count is 1
[0. 1. 0.]
36442 for count is 0
[1. 0. 0.]
36443 for count is 2
[0. 0. 1.]
36444 for count is 1
[0. 1. 0.]
36445 for count is 2
[0. 0. 1

[1. 0. 0.]
37048 for count is 2
[0. 0. 1.]
37049 for count is 1
[0. 1. 0.]
37050 for count is 1
[0. 1. 0.]
37051 for count is 1
[0. 1. 0.]
37052 for count is 2
[0. 0. 1.]
37053 for count is 1
[0. 1. 0.]
37054 for count is 0
[1. 0. 0.]
37055 for count is 2
[0. 0. 1.]
37056 for count is 1
[0. 1. 0.]
37057 for count is 2
[0. 0. 1.]
37058 for count is 2
[0. 0. 1.]
37059 for count is 2
[0. 0. 1.]
37060 for count is 2
[0. 0. 1.]
37061 for count is 2
[0. 0. 1.]
37062 for count is 1
[0. 1. 0.]
37063 for count is 2
[0. 0. 1.]
37064 for count is 2
[0. 0. 1.]
37065 for count is 1
[0. 1. 0.]
37066 for count is 2
[0. 0. 1.]
37067 for count is 0
[1. 0. 0.]
37068 for count is 1
[0. 1. 0.]
37069 for count is 2
[0. 0. 1.]
37070 for count is 1
[0. 1. 0.]
37071 for count is 0
[1. 0. 0.]
37072 for count is 0
[1. 0. 0.]
37073 for count is 2
[0. 0. 1.]
37074 for count is 0
[1. 0. 0.]
37075 for count is 1
[0. 1. 0.]
37076 for count is 2
[0. 0. 1.]
37077 for count is 2
[0. 0. 1.]
37078 for count is 0
[1. 0. 0

[0. 0. 1.]
37559 for count is 2
[0. 0. 1.]
37560 for count is 2
[0. 0. 1.]
37561 for count is 1
[0. 1. 0.]
37562 for count is 2
[0. 0. 1.]
37563 for count is 2
[0. 0. 1.]
37564 for count is 1
[0. 1. 0.]
37565 for count is 2
[0. 0. 1.]
37566 for count is 0
[1. 0. 0.]
37567 for count is 2
[0. 0. 1.]
37568 for count is 2
[0. 0. 1.]
37569 for count is 1
[0. 1. 0.]
37570 for count is 1
[0. 1. 0.]
37571 for count is 0
[1. 0. 0.]
37572 for count is 2
[0. 0. 1.]
37573 for count is 1
[0. 1. 0.]
37574 for count is 0
[1. 0. 0.]
37575 for count is 2
[0. 0. 1.]
37576 for count is 2
[0. 0. 1.]
37577 for count is 2
[0. 0. 1.]
37578 for count is 1
[0. 1. 0.]
37579 for count is 1
[0. 1. 0.]
37580 for count is 2
[0. 0. 1.]
37581 for count is 0
[1. 0. 0.]
37582 for count is 1
[0. 1. 0.]
37583 for count is 0
[1. 0. 0.]
37584 for count is 2
[0. 0. 1.]
37585 for count is 1
[0. 1. 0.]
37586 for count is 2
[0. 0. 1.]
37587 for count is 0
[1. 0. 0.]
37588 for count is 1
[0. 1. 0.]
37589 for count is 1
[0. 1. 0

[0. 0. 1.]
38283 for count is 2
[0. 0. 1.]
38284 for count is 1
[0. 1. 0.]
38285 for count is 0
[1. 0. 0.]
38286 for count is 2
[0. 0. 1.]
38287 for count is 2
[0. 0. 1.]
38288 for count is 2
[0. 0. 1.]
38289 for count is 0
[1. 0. 0.]
38290 for count is 1
[0. 1. 0.]
38291 for count is 2
[0. 0. 1.]
38292 for count is 2
[0. 0. 1.]
38293 for count is 2
[0. 0. 1.]
38294 for count is 1
[0. 1. 0.]
38295 for count is 2
[0. 0. 1.]
38296 for count is 1
[0. 1. 0.]
38297 for count is 2
[0. 0. 1.]
38298 for count is 1
[0. 1. 0.]
38299 for count is 0
[1. 0. 0.]
38300 for count is 1
[0. 1. 0.]
38301 for count is 2
[0. 0. 1.]
38302 for count is 0
[1. 0. 0.]
38303 for count is 1
[0. 1. 0.]
38304 for count is 1
[0. 1. 0.]
38305 for count is 2
[0. 0. 1.]
38306 for count is 2
[0. 0. 1.]
38307 for count is 2
[0. 0. 1.]
38308 for count is 1
[0. 1. 0.]
38309 for count is 1
[0. 1. 0.]
38310 for count is 0
[1. 0. 0.]
38311 for count is 2
[0. 0. 1.]
38312 for count is 0
[1. 0. 0.]
38313 for count is 1
[0. 1. 0

[0. 0. 1.]
39087 for count is 2
[0. 0. 1.]
39088 for count is 2
[0. 0. 1.]
39089 for count is 2
[0. 0. 1.]
39090 for count is 0
[1. 0. 0.]
39091 for count is 2
[0. 0. 1.]
39092 for count is 2
[0. 0. 1.]
39093 for count is 1
[0. 1. 0.]
39094 for count is 1
[0. 1. 0.]
39095 for count is 1
[0. 1. 0.]
39096 for count is 2
[0. 0. 1.]
39097 for count is 2
[0. 0. 1.]
39098 for count is 1
[0. 1. 0.]
39099 for count is 2
[0. 0. 1.]
39100 for count is 1
[0. 1. 0.]
39101 for count is 1
[0. 1. 0.]
39102 for count is 2
[0. 0. 1.]
39103 for count is 0
[1. 0. 0.]
39104 for count is 2
[0. 0. 1.]
39105 for count is 2
[0. 0. 1.]
39106 for count is 0
[1. 0. 0.]
39107 for count is 0
[1. 0. 0.]
39108 for count is 0
[1. 0. 0.]
39109 for count is 2
[0. 0. 1.]
39110 for count is 1
[0. 1. 0.]
39111 for count is 0
[1. 0. 0.]
39112 for count is 2
[0. 0. 1.]
39113 for count is 0
[1. 0. 0.]
39114 for count is 1
[0. 1. 0.]
39115 for count is 1
[0. 1. 0.]
39116 for count is 1
[0. 1. 0.]
39117 for count is 2
[0. 0. 1

[1. 0. 0.]
39817 for count is 2
[0. 0. 1.]
39818 for count is 0
[1. 0. 0.]
39819 for count is 0
[1. 0. 0.]
39820 for count is 1
[0. 1. 0.]
39821 for count is 2
[0. 0. 1.]
39822 for count is 1
[0. 1. 0.]
39823 for count is 1
[0. 1. 0.]
39824 for count is 1
[0. 1. 0.]
39825 for count is 0
[1. 0. 0.]
39826 for count is 2
[0. 0. 1.]
39827 for count is 1
[0. 1. 0.]
39828 for count is 2
[0. 0. 1.]
39829 for count is 2
[0. 0. 1.]
39830 for count is 0
[1. 0. 0.]
39831 for count is 0
[1. 0. 0.]
39832 for count is 1
[0. 1. 0.]
39833 for count is 1
[0. 1. 0.]
39834 for count is 1
[0. 1. 0.]
39835 for count is 2
[0. 0. 1.]
39836 for count is 2
[0. 0. 1.]
39837 for count is 2
[0. 0. 1.]
39838 for count is 1
[0. 1. 0.]
39839 for count is 2
[0. 0. 1.]
39840 for count is 2
[0. 0. 1.]
39841 for count is 2
[0. 0. 1.]
39842 for count is 2
[0. 0. 1.]
39843 for count is 1
[0. 1. 0.]
39844 for count is 2
[0. 0. 1.]
39845 for count is 1
[0. 1. 0.]
39846 for count is 2
[0. 0. 1.]
39847 for count is 2
[0. 0. 1

[0. 1. 0.]
40601 for count is 0
[1. 0. 0.]
40602 for count is 1
[0. 1. 0.]
40603 for count is 2
[0. 0. 1.]
40604 for count is 0
[1. 0. 0.]
40605 for count is 1
[0. 1. 0.]
40606 for count is 2
[0. 0. 1.]
40607 for count is 2
[0. 0. 1.]
40608 for count is 1
[0. 1. 0.]
40609 for count is 0
[1. 0. 0.]
40610 for count is 1
[0. 1. 0.]
40611 for count is 1
[0. 1. 0.]
40612 for count is 2
[0. 0. 1.]
40613 for count is 2
[0. 0. 1.]
40614 for count is 1
[0. 1. 0.]
40615 for count is 2
[0. 0. 1.]
40616 for count is 2
[0. 0. 1.]
40617 for count is 2
[0. 0. 1.]
40618 for count is 2
[0. 0. 1.]
40619 for count is 0
[1. 0. 0.]
40620 for count is 2
[0. 0. 1.]
40621 for count is 2
[0. 0. 1.]
40622 for count is 2
[0. 0. 1.]
40623 for count is 1
[0. 1. 0.]
40624 for count is 0
[1. 0. 0.]
40625 for count is 1
[0. 1. 0.]
40626 for count is 0
[1. 0. 0.]
40627 for count is 1
[0. 1. 0.]
40628 for count is 1
[0. 1. 0.]
40629 for count is 2
[0. 0. 1.]
40630 for count is 0
[1. 0. 0.]
40631 for count is 2
[0. 0. 1

[0. 0. 1.]
41321 for count is 2
[0. 0. 1.]
41322 for count is 1
[0. 1. 0.]
41323 for count is 0
[1. 0. 0.]
41324 for count is 2
[0. 0. 1.]
41325 for count is 1
[0. 1. 0.]
41326 for count is 1
[0. 1. 0.]
41327 for count is 2
[0. 0. 1.]
41328 for count is 0
[1. 0. 0.]
41329 for count is 1
[0. 1. 0.]
41330 for count is 0
[1. 0. 0.]
41331 for count is 2
[0. 0. 1.]
41332 for count is 0
[1. 0. 0.]
41333 for count is 1
[0. 1. 0.]
41334 for count is 2
[0. 0. 1.]
41335 for count is 2
[0. 0. 1.]
41336 for count is 2
[0. 0. 1.]
41337 for count is 0
[1. 0. 0.]
41338 for count is 1
[0. 1. 0.]
41339 for count is 2
[0. 0. 1.]
41340 for count is 0
[1. 0. 0.]
41341 for count is 1
[0. 1. 0.]
41342 for count is 0
[1. 0. 0.]
41343 for count is 1
[0. 1. 0.]
41344 for count is 2
[0. 0. 1.]
41345 for count is 0
[1. 0. 0.]
41346 for count is 2
[0. 0. 1.]
41347 for count is 2
[0. 0. 1.]
41348 for count is 0
[1. 0. 0.]
41349 for count is 0
[1. 0. 0.]
41350 for count is 2
[0. 0. 1.]
41351 for count is 2
[0. 0. 1

42070 for count is 2
[0. 0. 1.]
42071 for count is 2
[0. 0. 1.]
42072 for count is 0
[1. 0. 0.]
42073 for count is 2
[0. 0. 1.]
42074 for count is 1
[0. 1. 0.]
42075 for count is 1
[0. 1. 0.]
42076 for count is 0
[1. 0. 0.]
42077 for count is 2
[0. 0. 1.]
42078 for count is 2
[0. 0. 1.]
42079 for count is 1
[0. 1. 0.]
42080 for count is 1
[0. 1. 0.]
42081 for count is 1
[0. 1. 0.]
42082 for count is 2
[0. 0. 1.]
42083 for count is 2
[0. 0. 1.]
42084 for count is 1
[0. 1. 0.]
42085 for count is 0
[1. 0. 0.]
42086 for count is 1
[0. 1. 0.]
42087 for count is 1
[0. 1. 0.]
42088 for count is 1
[0. 1. 0.]
42089 for count is 2
[0. 0. 1.]
42090 for count is 2
[0. 0. 1.]
42091 for count is 1
[0. 1. 0.]
42092 for count is 0
[1. 0. 0.]
42093 for count is 1
[0. 1. 0.]
42094 for count is 0
[1. 0. 0.]
42095 for count is 1
[0. 1. 0.]
42096 for count is 2
[0. 0. 1.]
42097 for count is 2
[0. 0. 1.]
42098 for count is 2
[0. 0. 1.]
42099 for count is 1
[0. 1. 0.]
42100 for count is 0
[1. 0. 0.]
42101 fo

[0. 1. 0.]
42759 for count is 1
[0. 1. 0.]
42760 for count is 2
[0. 0. 1.]
42761 for count is 0
[1. 0. 0.]
42762 for count is 1
[0. 1. 0.]
42763 for count is 2
[0. 0. 1.]
42764 for count is 1
[0. 1. 0.]
42765 for count is 2
[0. 0. 1.]
42766 for count is 2
[0. 0. 1.]
42767 for count is 1
[0. 1. 0.]
42768 for count is 1
[0. 1. 0.]
42769 for count is 1
[0. 1. 0.]
42770 for count is 2
[0. 0. 1.]
42771 for count is 2
[0. 0. 1.]
42772 for count is 2
[0. 0. 1.]
42773 for count is 2
[0. 0. 1.]
42774 for count is 1
[0. 1. 0.]
42775 for count is 0
[1. 0. 0.]
42776 for count is 2
[0. 0. 1.]
42777 for count is 2
[0. 0. 1.]
42778 for count is 1
[0. 1. 0.]
42779 for count is 1
[0. 1. 0.]
42780 for count is 1
[0. 1. 0.]
42781 for count is 2
[0. 0. 1.]
42782 for count is 0
[1. 0. 0.]
42783 for count is 2
[0. 0. 1.]
42784 for count is 1
[0. 1. 0.]
42785 for count is 2
[0. 0. 1.]
42786 for count is 2
[0. 0. 1.]
42787 for count is 0
[1. 0. 0.]
42788 for count is 2
[0. 0. 1.]
42789 for count is 2
[0. 0. 1

[0. 1. 0.]
43311 for count is 1
[0. 1. 0.]
43312 for count is 1
[0. 1. 0.]
43313 for count is 1
[0. 1. 0.]
43314 for count is 1
[0. 1. 0.]
43315 for count is 2
[0. 0. 1.]
43316 for count is 1
[0. 1. 0.]
43317 for count is 1
[0. 1. 0.]
43318 for count is 2
[0. 0. 1.]
43319 for count is 2
[0. 0. 1.]
43320 for count is 2
[0. 0. 1.]
43321 for count is 2
[0. 0. 1.]
43322 for count is 1
[0. 1. 0.]
43323 for count is 1
[0. 1. 0.]
43324 for count is 0
[1. 0. 0.]
43325 for count is 2
[0. 0. 1.]
43326 for count is 1
[0. 1. 0.]
43327 for count is 1
[0. 1. 0.]
43328 for count is 2
[0. 0. 1.]
43329 for count is 1
[0. 1. 0.]
43330 for count is 0
[1. 0. 0.]
43331 for count is 1
[0. 1. 0.]
43332 for count is 2
[0. 0. 1.]
43333 for count is 2
[0. 0. 1.]
43334 for count is 1
[0. 1. 0.]
43335 for count is 1
[0. 1. 0.]
43336 for count is 1
[0. 1. 0.]
43337 for count is 0
[1. 0. 0.]
43338 for count is 1
[0. 1. 0.]
43339 for count is 2
[0. 0. 1.]
43340 for count is 1
[0. 1. 0.]
43341 for count is 2
[0. 0. 1

[0. 1. 0.]
43966 for count is 0
[1. 0. 0.]
43967 for count is 1
[0. 1. 0.]
43968 for count is 2
[0. 0. 1.]
43969 for count is 2
[0. 0. 1.]
43970 for count is 2
[0. 0. 1.]
43971 for count is 0
[1. 0. 0.]
43972 for count is 0
[1. 0. 0.]
43973 for count is 0
[1. 0. 0.]
43974 for count is 0
[1. 0. 0.]
43975 for count is 1
[0. 1. 0.]
43976 for count is 2
[0. 0. 1.]
43977 for count is 1
[0. 1. 0.]
43978 for count is 1
[0. 1. 0.]
43979 for count is 1
[0. 1. 0.]
43980 for count is 1
[0. 1. 0.]
43981 for count is 0
[1. 0. 0.]
43982 for count is 1
[0. 1. 0.]
43983 for count is 1
[0. 1. 0.]
43984 for count is 2
[0. 0. 1.]
43985 for count is 0
[1. 0. 0.]
43986 for count is 2
[0. 0. 1.]
43987 for count is 0
[1. 0. 0.]
43988 for count is 1
[0. 1. 0.]
43989 for count is 1
[0. 1. 0.]
43990 for count is 2
[0. 0. 1.]
43991 for count is 1
[0. 1. 0.]
43992 for count is 2
[0. 0. 1.]
43993 for count is 2
[0. 0. 1.]
43994 for count is 1
[0. 1. 0.]
43995 for count is 0
[1. 0. 0.]
43996 for count is 2
[0. 0. 1

[0. 0. 1.]
44811 for count is 1
[0. 1. 0.]
44812 for count is 0
[1. 0. 0.]
44813 for count is 1
[0. 1. 0.]
44814 for count is 2
[0. 0. 1.]
44815 for count is 2
[0. 0. 1.]
44816 for count is 1
[0. 1. 0.]
44817 for count is 1
[0. 1. 0.]
44818 for count is 2
[0. 0. 1.]
44819 for count is 2
[0. 0. 1.]
44820 for count is 0
[1. 0. 0.]
44821 for count is 1
[0. 1. 0.]
44822 for count is 1
[0. 1. 0.]
44823 for count is 2
[0. 0. 1.]
44824 for count is 1
[0. 1. 0.]
44825 for count is 2
[0. 0. 1.]
44826 for count is 2
[0. 0. 1.]
44827 for count is 0
[1. 0. 0.]
44828 for count is 1
[0. 1. 0.]
44829 for count is 0
[1. 0. 0.]
44830 for count is 2
[0. 0. 1.]
44831 for count is 2
[0. 0. 1.]
44832 for count is 1
[0. 1. 0.]
44833 for count is 2
[0. 0. 1.]
44834 for count is 2
[0. 0. 1.]
44835 for count is 2
[0. 0. 1.]
44836 for count is 2
[0. 0. 1.]
44837 for count is 0
[1. 0. 0.]
44838 for count is 1
[0. 1. 0.]
44839 for count is 1
[0. 1. 0.]
44840 for count is 1
[0. 1. 0.]
44841 for count is 2
[0. 0. 1

[0. 0. 1.]
45615 for count is 1
[0. 1. 0.]
45616 for count is 1
[0. 1. 0.]
45617 for count is 1
[0. 1. 0.]
45618 for count is 2
[0. 0. 1.]
45619 for count is 1
[0. 1. 0.]
45620 for count is 1
[0. 1. 0.]
45621 for count is 2
[0. 0. 1.]
45622 for count is 2
[0. 0. 1.]
45623 for count is 2
[0. 0. 1.]
45624 for count is 0
[1. 0. 0.]
45625 for count is 0
[1. 0. 0.]
45626 for count is 2
[0. 0. 1.]
45627 for count is 1
[0. 1. 0.]
45628 for count is 0
[1. 0. 0.]
45629 for count is 0
[1. 0. 0.]
45630 for count is 2
[0. 0. 1.]
45631 for count is 2
[0. 0. 1.]
45632 for count is 2
[0. 0. 1.]
45633 for count is 0
[1. 0. 0.]
45634 for count is 0
[1. 0. 0.]
45635 for count is 2
[0. 0. 1.]
45636 for count is 2
[0. 0. 1.]
45637 for count is 1
[0. 1. 0.]
45638 for count is 1
[0. 1. 0.]
45639 for count is 1
[0. 1. 0.]
45640 for count is 2
[0. 0. 1.]
45641 for count is 1
[0. 1. 0.]
45642 for count is 2
[0. 0. 1.]
45643 for count is 2
[0. 0. 1.]
45644 for count is 2
[0. 0. 1.]
45645 for count is 1
[0. 1. 0

[0. 1. 0.]
46266 for count is 2
[0. 0. 1.]
46267 for count is 1
[0. 1. 0.]
46268 for count is 1
[0. 1. 0.]
46269 for count is 2
[0. 0. 1.]
46270 for count is 1
[0. 1. 0.]
46271 for count is 2
[0. 0. 1.]
46272 for count is 2
[0. 0. 1.]
46273 for count is 1
[0. 1. 0.]
46274 for count is 0
[1. 0. 0.]
46275 for count is 2
[0. 0. 1.]
46276 for count is 1
[0. 1. 0.]
46277 for count is 0
[1. 0. 0.]
46278 for count is 0
[1. 0. 0.]
46279 for count is 2
[0. 0. 1.]
46280 for count is 2
[0. 0. 1.]
46281 for count is 2
[0. 0. 1.]
46282 for count is 2
[0. 0. 1.]
46283 for count is 0
[1. 0. 0.]
46284 for count is 1
[0. 1. 0.]
46285 for count is 1
[0. 1. 0.]
46286 for count is 0
[1. 0. 0.]
46287 for count is 2
[0. 0. 1.]
46288 for count is 1
[0. 1. 0.]
46289 for count is 1
[0. 1. 0.]
46290 for count is 2
[0. 0. 1.]
46291 for count is 1
[0. 1. 0.]
46292 for count is 1
[0. 1. 0.]
46293 for count is 2
[0. 0. 1.]
46294 for count is 0
[1. 0. 0.]
46295 for count is 1
[0. 1. 0.]
46296 for count is 2
[0. 0. 1

[0. 1. 0.]
46899 for count is 2
[0. 0. 1.]
46900 for count is 1
[0. 1. 0.]
46901 for count is 2
[0. 0. 1.]
46902 for count is 1
[0. 1. 0.]
46903 for count is 1
[0. 1. 0.]
46904 for count is 0
[1. 0. 0.]
46905 for count is 2
[0. 0. 1.]
46906 for count is 1
[0. 1. 0.]
46907 for count is 2
[0. 0. 1.]
46908 for count is 2
[0. 0. 1.]
46909 for count is 2
[0. 0. 1.]
46910 for count is 1
[0. 1. 0.]
46911 for count is 2
[0. 0. 1.]
46912 for count is 0
[1. 0. 0.]
46913 for count is 2
[0. 0. 1.]
46914 for count is 0
[1. 0. 0.]
46915 for count is 1
[0. 1. 0.]
46916 for count is 2
[0. 0. 1.]
46917 for count is 1
[0. 1. 0.]
46918 for count is 0
[1. 0. 0.]
46919 for count is 1
[0. 1. 0.]
46920 for count is 2
[0. 0. 1.]
46921 for count is 1
[0. 1. 0.]
46922 for count is 1
[0. 1. 0.]
46923 for count is 1
[0. 1. 0.]
46924 for count is 2
[0. 0. 1.]
46925 for count is 1
[0. 1. 0.]
46926 for count is 2
[0. 0. 1.]
46927 for count is 2
[0. 0. 1.]
46928 for count is 1
[0. 1. 0.]
46929 for count is 0
[1. 0. 0

[0. 0. 1.]
47594 for count is 1
[0. 1. 0.]
47595 for count is 2
[0. 0. 1.]
47596 for count is 2
[0. 0. 1.]
47597 for count is 2
[0. 0. 1.]
47598 for count is 1
[0. 1. 0.]
47599 for count is 2
[0. 0. 1.]
47600 for count is 0
[1. 0. 0.]
47601 for count is 1
[0. 1. 0.]
47602 for count is 1
[0. 1. 0.]
47603 for count is 0
[1. 0. 0.]
47604 for count is 2
[0. 0. 1.]
47605 for count is 2
[0. 0. 1.]
47606 for count is 1
[0. 1. 0.]
47607 for count is 2
[0. 0. 1.]
47608 for count is 0
[1. 0. 0.]
47609 for count is 1
[0. 1. 0.]
47610 for count is 2
[0. 0. 1.]
47611 for count is 0
[1. 0. 0.]
47612 for count is 2
[0. 0. 1.]
47613 for count is 0
[1. 0. 0.]
47614 for count is 1
[0. 1. 0.]
47615 for count is 1
[0. 1. 0.]
47616 for count is 0
[1. 0. 0.]
47617 for count is 1
[0. 1. 0.]
47618 for count is 1
[0. 1. 0.]
47619 for count is 1
[0. 1. 0.]
47620 for count is 0
[1. 0. 0.]
47621 for count is 2
[0. 0. 1.]
47622 for count is 1
[0. 1. 0.]
47623 for count is 2
[0. 0. 1.]
47624 for count is 2
[0. 0. 1

[0. 0. 1.]
48335 for count is 2
[0. 0. 1.]
48336 for count is 2
[0. 0. 1.]
48337 for count is 2
[0. 0. 1.]
48338 for count is 2
[0. 0. 1.]
48339 for count is 1
[0. 1. 0.]
48340 for count is 2
[0. 0. 1.]
48341 for count is 2
[0. 0. 1.]
48342 for count is 2
[0. 0. 1.]
48343 for count is 2
[0. 0. 1.]
48344 for count is 2
[0. 0. 1.]
48345 for count is 2
[0. 0. 1.]
48346 for count is 0
[1. 0. 0.]
48347 for count is 1
[0. 1. 0.]
48348 for count is 0
[1. 0. 0.]
48349 for count is 0
[1. 0. 0.]
48350 for count is 2
[0. 0. 1.]
48351 for count is 2
[0. 0. 1.]
48352 for count is 1
[0. 1. 0.]
48353 for count is 0
[1. 0. 0.]
48354 for count is 1
[0. 1. 0.]
48355 for count is 0
[1. 0. 0.]
48356 for count is 0
[1. 0. 0.]
48357 for count is 1
[0. 1. 0.]
48358 for count is 2
[0. 0. 1.]
48359 for count is 2
[0. 0. 1.]
48360 for count is 2
[0. 0. 1.]
48361 for count is 1
[0. 1. 0.]
48362 for count is 1
[0. 1. 0.]
48363 for count is 1
[0. 1. 0.]
48364 for count is 1
[0. 1. 0.]
48365 for count is 2
[0. 0. 1

## Testing accuracy:

In [44]:
Y_test

Negative  Neutral  Positive
148182         0        0         1
93407          0        0         1
41020          0        1         0
33568          0        1         0
50032          1        0         0
...          ...      ...       ...
58996          1        0         0
3755           0        1         0
150686         0        1         0
4987           0        0         1
51349          0        0         1

[48891 rows x 3 columns]

In [45]:
from sklearn.metrics import accuracy_score
print('Accuracy of the model:', accuracy_score(Y_test, pred))

Accuracy of the model: 0.7353705180912642


## 11. Classification report:

In [46]:
from sklearn.metrics import classification_report
print('Classification report:\n', classification_report(Y_test, pred))


Classification report:
               precision    recall  f1-score   support

           0       0.64      0.60      0.62     10607
           1       0.75      0.77      0.76     16561
           2       0.77      0.78      0.77     21723

   micro avg       0.74      0.74      0.74     48891
   macro avg       0.72      0.71      0.72     48891
weighted avg       0.73      0.74      0.73     48891
 samples avg       0.74      0.74      0.74     48891



Thesis:
    
    1. Performed Data handling by loading the dataset, reviewing its dimensional information, analyzing its data.
    2. Carried-out text-correction by converting text into lower-case, removing all non-alphabetic charaters from it.
    3. Executed text-Preprocessing through stopwords removal, stemming(rooting the word into its root word), lemmatizing(converting to its dictionary form) process.
    4. Built LSTM model for generating classification results and evaluated using test data.
    5. Tested results by performance metrics.